-- NAME: OfflineAIMap
-- TIME: 2014.3.11-20:14:1
-- Generated by editor

GameData = GameData or {}
GameData.OfflineAIMap= {
	["offlineAIMap_1"] = { refId = "offlineAIMap_1", minLevelId = 20, maxLevelId = 23, mapId = "S034",},
	["offlineAIMap_10"] = { refId = "offlineAIMap_10", minLevelId = 47, maxLevelId = 50, mapId = "S040",},
	["offlineAIMap_11"] = { refId = "offlineAIMap_11", minLevelId = 51, maxLevelId = 55, mapId = "S041",},
	["offlineAIMap_12"] = { refId = "offlineAIMap_12", minLevelId = 56, maxLevelId = 60, mapId = "S042",},
	["offlineAIMap_13"] = { refId = "offlineAIMap_13", minLevelId = 61, maxLevelId = 65, mapId = "S047",},
	["offlineAIMap_14"] = { refId = "offlineAIMap_14", minLevelId = 66, maxLevelId = 70, mapId = "S048",},
	["offlineAIMap_15"] = { refId = "offlineAIMap_15", minLevelId = 71, maxLevelId = 75, mapId = "S045",},
	["offlineAIMap_16"] = { refId = "offlineAIMap_16", minLevelId = 76, maxLevelId = 100, mapId = "S046",},
	["offlineAIMap_2"] = { refId = "offlineAIMap_2", minLevelId = 24, maxLevelId = 25, mapId = "S033",},
	["offlineAIMap_3"] = { refId = "offlineAIMap_3", minLevelId = 26, maxLevelId = 28, mapId = "S031",},
	["offlineAIMap_4"] = { refId = "offlineAIMap_4", minLevelId = 29, maxLevelId = 30, mapId = "S032",},
	["offlineAIMap_5"] = { refId = "offlineAIMap_5", minLevelId = 31, maxLevelId = 33, mapId = "S035",},
	["offlineAIMap_6"] = { refId = "offlineAIMap_6", minLevelId = 34, maxLevelId = 35, mapId = "S036",},
	["offlineAIMap_7"] = { refId = "offlineAIMap_7", minLevelId = 36, maxLevelId = 40, mapId = "S037",},
	["offlineAIMap_8"] = { refId = "offlineAIMap_8", minLevelId = 41, maxLevelId = 42, mapId = "S038",},
	["offlineAIMap_9"] = { refId = "offlineAIMap_9", minLevelId = 43, maxLevelId = 46, mapId = "S039",}
}
