-- NAME: DataSave
-- TIME: 2014.7.7-21:22:12
-- Generated by editor

GameData = GameData or {}
GameData.DataSave= {
	["activity_manage_16"] = { refId = "activity_manage_16", name = "VIP抽奖",},
	["activity_manage_17"] = { refId = "activity_manage_17", name = "开服冲级（限时速冲）",},
	["activity_manage_2"] = { refId = "activity_manage_2", name = "7日登陆",},
	["activity_manage_3"] = { refId = "activity_manage_3", name = "在线时长奖励",},
	["activity_manage_5"] = { refId = "activity_manage_5", name = "竞技场",},
	["activity_manage_6"] = { refId = "activity_manage_6", name = "怪物入侵",},
	["activity_manage_7"] = { refId = "activity_manage_7", name = "挖矿",},
	["handUpSkillGuidence"] = { refId = "handUpSkillGuidence", name = "挂机技能引导",}
}
