-- NAME: Mall
-- TIME: 2014.7.22-15:48:31
-- Generated by editor

GameData = GameData or {}
GameData.Mall= {
	["mall_item_001"] = { refId = "mall_item_001", property = { storeType = "mall_1", itemId = "item_vip_1", itemSellType = 3, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 2000, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 4000, refId = "unbindedGold", },}, }, },
	["mall_item_002"] = { refId = "mall_item_002", property = { storeType = "mall_1", itemId = "item_vip_3", itemSellType = 3, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 8000, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 16000, refId = "unbindedGold", },}, }, },
	["mall_item_003"] = { refId = "mall_item_003", property = { storeType = "mall_1", itemId = "item_drug_9", itemSellType = 3, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 5, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 10, refId = "unbindedGold", },}, }, },
	["mall_item_004"] = { refId = "mall_item_004", property = { storeType = "mall_1", itemId = "item_lingpai_1", itemSellType = 3, itemLimitType = 1, itemLimitNum = 10, number = 1, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 300, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 600, refId = "unbindedGold", },}, }, },
	["mall_item_005"] = { refId = "mall_item_005", property = { storeType = "mall_1", itemId = "item_lingpai_3", itemSellType = 3, itemLimitType = 1, itemLimitNum = 10, number = 1, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 300, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 600, refId = "unbindedGold", },}, }, },
	["mall_item_006"] = { refId = "mall_item_006", property = { storeType = "mall_1", itemId = "item_zhenmoling_1", itemSellType = 3, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 10, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 40, refId = "unbindedGold", },}, }, },
	["mall_item_007"] = { refId = "mall_item_007", property = { storeType = "mall_1", itemId = "item_superluck", itemSellType = 3, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 8888, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 17776, refId = "unbindedGold", },}, }, },
	["mall_item_008"] = { refId = "mall_item_008", property = { storeType = "mall_1", itemId = "item_zuoqiExp", itemSellType = 3, itemLimitType = 1, itemLimitNum = 2000, number = 1, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 20, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 40, refId = "unbindedGold", },}, }, },
	["mall_item_009"] = { refId = "mall_item_009", property = { storeType = "mall_1", itemId = "item_duihuanquan_2", itemSellType = 3, itemLimitType = 1, itemLimitNum = 10, number = 1, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 100, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 200, refId = "unbindedGold", },}, }, },
	["mall_item_010"] = { refId = "mall_item_010", property = { storeType = "mall_1", itemId = "item_duihuanquan_1", itemSellType = 3, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 50, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 100, refId = "unbindedGold", },}, }, },
	["mall_item_011"] = { refId = "mall_item_011", property = { storeType = "mall_1", itemId = "item_chibangExp", itemSellType = 3, itemLimitType = 1, itemLimitNum = 2000, number = 1, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 20, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 40, refId = "unbindedGold", },}, }, },
	["mall_item_012"] = { refId = "mall_item_012", property = { storeType = "mall_1", itemId = "item_shenqiExp", itemSellType = 3, itemLimitType = 1, itemLimitNum = 2000, number = 1, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 40, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 80, refId = "unbindedGold", },}, }, },
	["mall_item_013"] = { refId = "mall_item_013", property = { storeType = "mall_1", itemId = "item_pk0", itemSellType = 3, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 400, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 800, refId = "unbindedGold", },}, }, },
	["mall_item_014"] = { refId = "mall_item_014", property = { storeType = "mall_1", itemId = "item_3exp", itemSellType = 3, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 188, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 376, refId = "unbindedGold", },}, }, },
	["mall_item_015"] = { refId = "mall_item_015", property = { storeType = "mall_1", itemId = "item_2exp", itemSellType = 3, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 100, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 200, refId = "unbindedGold", },}, }, },
	["mall_item_016"] = { refId = "mall_item_016", property = { storeType = "mall_1", itemId = "item_jinengExp", itemSellType = 3, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 100, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 200, refId = "unbindedGold", },}, }, },
	["mall_item_017"] = { refId = "mall_item_017", property = { storeType = "mall_1", itemId = "item_danyao_1", itemSellType = 3, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 200, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 400, refId = "unbindedGold", },}, }, },
	["mall_item_018"] = { refId = "mall_item_018", property = { storeType = "mall_1", itemId = "item_danyao_2", itemSellType = 3, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 200, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 400, refId = "unbindedGold", },}, }, },
	["mall_item_019"] = { refId = "mall_item_019", property = { storeType = "mall_1", itemId = "item_danyao_3", itemSellType = 3, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 200, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 400, refId = "unbindedGold", },}, }, },
	["mall_item_020"] = { refId = "mall_item_020", property = { storeType = "mall_1", itemId = "item_danyao_4", itemSellType = 3, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 200, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 400, refId = "unbindedGold", },}, }, },
	["mall_item_021"] = { refId = "mall_item_021", property = { storeType = "mall_1", itemId = "item_danyao_5", itemSellType = 3, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 200, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 400, refId = "unbindedGold", },}, }, },
	["mall_item_022"] = { refId = "mall_item_022", property = { storeType = "mall_1", itemId = "item_moveto_3", itemSellType = 3, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 5, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 10, refId = "unbindedGold", },}, }, },
	["mall_item_023"] = { refId = "mall_item_023", property = { storeType = "mall_1", itemId = "item_horn", itemSellType = 3, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 1000, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 2000, refId = "unbindedGold", },}, }, },
	["mall_item_024"] = { refId = "mall_item_024", property = { storeType = "mall_1", itemId = "item_gonghuiling", itemSellType = 3, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 1000, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 2000, refId = "unbindedGold", },}, }, },
	["mall_item_025"] = { refId = "mall_item_025", property = { storeType = "mall_1", itemId = "item_gongcheng", itemSellType = 3, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 1000, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 2000, refId = "unbindedGold", },}, }, },
	["mall_item_026"] = { refId = "mall_item_026", property = { storeType = "mall_1", itemId = "item_moxueshi_1", itemSellType = 3, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 100, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 200, refId = "unbindedGold", },}, }, },
	["mall_item_027"] = { refId = "mall_item_027", property = { storeType = "mall_1", itemId = "item_moxueshi_2", itemSellType = 3, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 200, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 400, refId = "unbindedGold", },}, }, },
	["mall_item_028"] = { refId = "mall_item_028", property = { storeType = "mall_1", itemId = "item_moxueshi_3", itemSellType = 3, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 400, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 800, refId = "unbindedGold", },}, }, },
	["mall_item_029"] = { refId = "mall_item_029", property = { storeType = "mall_1", itemId = "item_templetickets", itemSellType = 3, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 0,},  priceData = {
			 nowPriceData = { { number = 500, refId = "unbindedGold", },}, 
			 formerPriceData = { { number = 1000, refId = "unbindedGold", },}, }, },
	["mall_item_030"] = { refId = "mall_item_030", property = { storeType = "mall_2", itemId = "item_lingpai_3", itemSellType = 0, itemLimitType = 1, itemLimitNum = 5, number = 1, storeLimitTime = "", bindStatus = 1,},  priceData = {
			 nowPriceData = { { number = 600, refId = "bindedGold", },}, 
			 formerPriceData = "", }, },
	["mall_item_031"] = { refId = "mall_item_031", property = { storeType = "mall_2", itemId = "item_zhenmoling_1", itemSellType = 0, itemLimitType = 1, itemLimitNum = 200, number = 1, storeLimitTime = "", bindStatus = 1,},  priceData = {
			 nowPriceData = { { number = 40, refId = "bindedGold", },}, 
			 formerPriceData = "", }, },
	["mall_item_032"] = { refId = "mall_item_032", property = { storeType = "mall_2", itemId = "item_zuoqiExp", itemSellType = 0, itemLimitType = 1, itemLimitNum = 100, number = 1, storeLimitTime = "", bindStatus = 1,},  priceData = {
			 nowPriceData = { { number = 40, refId = "bindedGold", },}, 
			 formerPriceData = "", }, },
	["mall_item_033"] = { refId = "mall_item_033", property = { storeType = "mall_2", itemId = "item_duihuanquan_2", itemSellType = 0, itemLimitType = 1, itemLimitNum = 5, number = 1, storeLimitTime = "", bindStatus = 1,},  priceData = {
			 nowPriceData = { { number = 200, refId = "bindedGold", },}, 
			 formerPriceData = "", }, },
	["mall_item_034"] = { refId = "mall_item_034", property = { storeType = "mall_2", itemId = "item_chibangExp", itemSellType = 0, itemLimitType = 1, itemLimitNum = 100, number = 1, storeLimitTime = "", bindStatus = 1,},  priceData = {
			 nowPriceData = { { number = 40, refId = "bindedGold", },}, 
			 formerPriceData = "", }, },
	["mall_item_035"] = { refId = "mall_item_035", property = { storeType = "mall_2", itemId = "item_shenqiExp", itemSellType = 0, itemLimitType = 1, itemLimitNum = 100, number = 1, storeLimitTime = "", bindStatus = 1,},  priceData = {
			 nowPriceData = { { number = 80, refId = "bindedGold", },}, 
			 formerPriceData = "", }, },
	["mall_item_036"] = { refId = "mall_item_036", property = { storeType = "mall_2", itemId = "item_luck", itemSellType = 0, itemLimitType = 1, itemLimitNum = 50, number = 1, storeLimitTime = "", bindStatus = 1,},  priceData = {
			 nowPriceData = { { number = 60, refId = "bindedGold", },}, 
			 formerPriceData = "", }, },
	["mall_item_037"] = { refId = "mall_item_037", property = { storeType = "mall_2", itemId = "item_2exp", itemSellType = 0, itemLimitType = 1, itemLimitNum = 5, number = 1, storeLimitTime = "", bindStatus = 1,},  priceData = {
			 nowPriceData = { { number = 200, refId = "bindedGold", },}, 
			 formerPriceData = "", }, },
	["mall_item_038"] = { refId = "mall_item_038", property = { storeType = "mall_2", itemId = "item_jinengExp", itemSellType = 0, itemLimitType = 1, itemLimitNum = 5, number = 1, storeLimitTime = "", bindStatus = 1,},  priceData = {
			 nowPriceData = { { number = 200, refId = "bindedGold", },}, 
			 formerPriceData = "", }, },
	["mall_item_039"] = { refId = "mall_item_039", property = { storeType = "mall_2", itemId = "item_danyao_1", itemSellType = 0, itemLimitType = 1, itemLimitNum = 5, number = 1, storeLimitTime = "", bindStatus = 1,},  priceData = {
			 nowPriceData = { { number = 400, refId = "bindedGold", },}, 
			 formerPriceData = "", }, },
	["mall_item_040"] = { refId = "mall_item_040", property = { storeType = "mall_2", itemId = "item_danyao_2", itemSellType = 0, itemLimitType = 1, itemLimitNum = 5, number = 1, storeLimitTime = "", bindStatus = 1,},  priceData = {
			 nowPriceData = { { number = 400, refId = "bindedGold", },}, 
			 formerPriceData = "", }, },
	["mall_item_041"] = { refId = "mall_item_041", property = { storeType = "mall_2", itemId = "item_danyao_3", itemSellType = 0, itemLimitType = 1, itemLimitNum = 5, number = 1, storeLimitTime = "", bindStatus = 1,},  priceData = {
			 nowPriceData = { { number = 400, refId = "bindedGold", },}, 
			 formerPriceData = "", }, },
	["mall_item_042"] = { refId = "mall_item_042", property = { storeType = "mall_2", itemId = "item_danyao_4", itemSellType = 0, itemLimitType = 1, itemLimitNum = 5, number = 1, storeLimitTime = "", bindStatus = 1,},  priceData = {
			 nowPriceData = { { number = 400, refId = "bindedGold", },}, 
			 formerPriceData = "", }, },
	["mall_item_043"] = { refId = "mall_item_043", property = { storeType = "mall_2", itemId = "item_danyao_5", itemSellType = 0, itemLimitType = 1, itemLimitNum = 5, number = 1, storeLimitTime = "", bindStatus = 1,},  priceData = {
			 nowPriceData = { { number = 400, refId = "bindedGold", },}, 
			 formerPriceData = "", }, },
	["mall_item_044"] = { refId = "mall_item_044", property = { storeType = "mall_2", itemId = "item_feixie", itemSellType = 0, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 1,},  priceData = {
			 nowPriceData = { { number = 10, refId = "bindedGold", },}, 
			 formerPriceData = "", }, },
	["mall_item_045"] = { refId = "mall_item_045", property = { storeType = "mall_2", itemId = "item_moxueshi_1", itemSellType = 0, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 1,},  priceData = {
			 nowPriceData = { { number = 200, refId = "bindedGold", },}, 
			 formerPriceData = "", }, },
	["mall_item_046"] = { refId = "mall_item_046", property = { storeType = "mall_2", itemId = "item_moxueshi_2", itemSellType = 0, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 1,},  priceData = {
			 nowPriceData = { { number = 400, refId = "bindedGold", },}, 
			 formerPriceData = "", }, },
	["mall_item_047"] = { refId = "mall_item_047", property = { storeType = "mall_2", itemId = "item_moxueshi_3", itemSellType = 0, itemLimitType = 0, itemLimitNum = 0, number = 0, storeLimitTime = "", bindStatus = 1,},  priceData = {
			 nowPriceData = { { number = 800, refId = "bindedGold", },}, 
			 formerPriceData = "", }, }
}
