-- NAME: Shop
-- TIME: 2014.7.10-21:59:17
-- Generated by editor

GameData = GameData or {}
GameData.Shop= {
	["shop_item_001"] = { refId = "shop_item_001", property = { storeType = "shop_1", itemId = "equip_15_1100", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 60000, refId = "gold", },}, }, },
	["shop_item_002"] = { refId = "shop_item_002", property = { storeType = "shop_1", itemId = "equip_15_1200", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 15000, refId = "gold", },}, }, },
	["shop_item_003"] = { refId = "shop_item_003", property = { storeType = "shop_1", itemId = "equip_15_1300", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 15000, refId = "gold", },}, }, },
	["shop_item_004"] = { refId = "shop_item_004", property = { storeType = "shop_1", itemId = "equip_20_1100", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 60000, refId = "gold", },}, }, },
	["shop_item_005"] = { refId = "shop_item_005", property = { storeType = "shop_1", itemId = "equip_20_1200", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 30000, refId = "gold", },}, }, },
	["shop_item_006"] = { refId = "shop_item_006", property = { storeType = "shop_1", itemId = "equip_20_1300", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 15000, refId = "gold", },}, }, },
	["shop_item_007"] = { refId = "shop_item_007", property = { storeType = "shop_1", itemId = "equip_25_1100", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 360000, refId = "gold", },}, }, },
	["shop_item_008"] = { refId = "shop_item_008", property = { storeType = "shop_1", itemId = "equip_25_1200", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 30000, refId = "gold", },}, }, },
	["shop_item_009"] = { refId = "shop_item_009", property = { storeType = "shop_1", itemId = "equip_25_1300", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 30000, refId = "gold", },}, }, },
	["shop_item_010"] = { refId = "shop_item_010", property = { storeType = "shop_2", itemId = "equip_20_2010", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 15000, refId = "gold", },}, }, },
	["shop_item_011"] = { refId = "shop_item_011", property = { storeType = "shop_2", itemId = "equip_20_2020", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 15000, refId = "gold", },}, }, },
	["shop_item_012"] = { refId = "shop_item_012", property = { storeType = "shop_2", itemId = "equip_20_3000", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 15000, refId = "gold", },}, }, },
	["shop_item_013"] = { refId = "shop_item_013", property = { storeType = "shop_3", itemId = "equip_25_6100", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 15000, refId = "gold", },}, }, },
	["shop_item_014"] = { refId = "shop_item_014", property = { storeType = "shop_3", itemId = "equip_25_6200", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 15000, refId = "gold", },}, }, },
	["shop_item_015"] = { refId = "shop_item_015", property = { storeType = "shop_3", itemId = "equip_25_6300", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 15000, refId = "gold", },}, }, },
	["shop_item_016"] = { refId = "shop_item_016", property = { storeType = "shop_3", itemId = "equip_25_7100", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 15000, refId = "gold", },}, }, },
	["shop_item_017"] = { refId = "shop_item_017", property = { storeType = "shop_3", itemId = "equip_25_7200", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 15000, refId = "gold", },}, }, },
	["shop_item_018"] = { refId = "shop_item_018", property = { storeType = "shop_3", itemId = "equip_25_7300", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 15000, refId = "gold", },}, }, },
	["shop_item_019"] = { refId = "shop_item_019", property = { storeType = "shop_3", itemId = "equip_25_8100", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 15000, refId = "gold", },}, }, },
	["shop_item_020"] = { refId = "shop_item_020", property = { storeType = "shop_3", itemId = "equip_25_8200", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 15000, refId = "gold", },}, }, },
	["shop_item_021"] = { refId = "shop_item_021", property = { storeType = "shop_3", itemId = "equip_25_8300", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 15000, refId = "gold", },}, }, },
	["shop_item_022"] = { refId = "shop_item_022", property = { storeType = "shop_4", itemId = "item_drug_1", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 20, refId = "gold", },}, }, },
	["shop_item_023"] = { refId = "shop_item_023", property = { storeType = "shop_4", itemId = "item_drug_2", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 50, refId = "gold", },}, }, },
	["shop_item_024"] = { refId = "shop_item_024", property = { storeType = "shop_4", itemId = "item_drug_3", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 100, refId = "gold", },}, }, },
	["shop_item_025"] = { refId = "shop_item_025", property = { storeType = "shop_4", itemId = "item_drug_4", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 20, refId = "gold", },}, }, },
	["shop_item_026"] = { refId = "shop_item_026", property = { storeType = "shop_4", itemId = "item_drug_5", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 50, refId = "gold", },}, }, },
	["shop_item_027"] = { refId = "shop_item_027", property = { storeType = "shop_4", itemId = "item_drug_6", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 100, refId = "gold", },}, }, },
	["shop_item_028"] = { refId = "shop_item_028", property = { storeType = "shop_4", itemId = "item_drug_7", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 1000, refId = "gold", },}, }, },
	["shop_item_029"] = { refId = "shop_item_029", property = { storeType = "shop_4", itemId = "item_drug_8", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 4000, refId = "gold", },}, }, },
	["shop_item_030"] = { refId = "shop_item_030", property = { storeType = "shop_4", itemId = "item_drug_9", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 10000, refId = "gold", },}, }, },
	["shop_item_031"] = { refId = "shop_item_031", property = { storeType = "shop_equip", itemId = "item_goldMedal", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 4, refId = "item_silverMedal", },}, }, },
	["shop_item_032"] = { refId = "shop_item_032", property = { storeType = "shop_equip", itemId = "item_silverMedal", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 3, refId = "item_copperMedal", },}, }, },
	["shop_item_033"] = { refId = "shop_item_033", property = { storeType = "shop_equip", itemId = "item_copperMedal", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 3, refId = "item_ironMedal", },}, }, },
	["shop_item_034"] = { refId = "shop_item_034", property = { storeType = "shop_equip", itemId = "item_silverMedal", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 1, refId = "item_goldMedal", },}, }, },
	["shop_item_035"] = { refId = "shop_item_035", property = { storeType = "shop_equip", itemId = "item_copperMedal", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 1, refId = "item_silverMedal", },}, }, },
	["shop_item_036"] = { refId = "shop_item_036", property = { storeType = "shop_equip", itemId = "item_ironMedal", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 1, refId = "item_copperMedal", },}, }, },
	["shop_item_037"] = { refId = "shop_item_037", property = { storeType = "shop_equip", itemId = "equip_40_1101", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 20, refId = "item_ironMedal", },}, }, },
	["shop_item_038"] = { refId = "shop_item_038", property = { storeType = "shop_equip", itemId = "equip_40_1202", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 20, refId = "item_ironMedal", },}, }, },
	["shop_item_039"] = { refId = "shop_item_039", property = { storeType = "shop_equip", itemId = "equip_40_1301", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 20, refId = "item_ironMedal", },}, }, },
	["shop_item_040"] = { refId = "shop_item_040", property = { storeType = "shop_equip", itemId = "equip_50_2111", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 60, refId = "item_ironMedal", },}, }, },
	["shop_item_041"] = { refId = "shop_item_041", property = { storeType = "shop_equip", itemId = "equip_50_2121", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 60, refId = "item_ironMedal", },}, }, },
	["shop_item_042"] = { refId = "shop_item_042", property = { storeType = "shop_equip", itemId = "equip_50_2212", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 60, refId = "item_ironMedal", },}, }, },
	["shop_item_043"] = { refId = "shop_item_043", property = { storeType = "shop_equip", itemId = "equip_50_2222", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 60, refId = "item_ironMedal", },}, }, },
	["shop_item_044"] = { refId = "shop_item_044", property = { storeType = "shop_equip", itemId = "equip_50_2312", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 60, refId = "item_ironMedal", },}, }, },
	["shop_item_045"] = { refId = "shop_item_045", property = { storeType = "shop_equip", itemId = "equip_50_2322", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 60, refId = "item_ironMedal", },}, }, },
	["shop_item_046"] = { refId = "shop_item_046", property = { storeType = "shop_equip", itemId = "equip_50_1104", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 100, refId = "item_copperMedal", },}, }, },
	["shop_item_047"] = { refId = "shop_item_047", property = { storeType = "shop_equip", itemId = "equip_50_1201", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 100, refId = "item_copperMedal", },}, }, },
	["shop_item_048"] = { refId = "shop_item_048", property = { storeType = "shop_equip", itemId = "equip_50_1305", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 100, refId = "item_copperMedal", },}, }, },
	["shop_item_049"] = { refId = "shop_item_049", property = { storeType = "shop_equip", itemId = "equip_50_6101", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 100, refId = "item_copperMedal", },}, }, },
	["shop_item_050"] = { refId = "shop_item_050", property = { storeType = "shop_equip", itemId = "equip_50_6201", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 100, refId = "item_copperMedal", },}, }, },
	["shop_item_051"] = { refId = "shop_item_051", property = { storeType = "shop_equip", itemId = "equip_50_6302", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 100, refId = "item_copperMedal", },}, }, },
	["shop_item_052"] = { refId = "shop_item_052", property = { storeType = "shop_equip", itemId = "equip_60_1103", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 300, refId = "item_silverMedal", },}, }, },
	["shop_item_053"] = { refId = "shop_item_053", property = { storeType = "shop_equip", itemId = "equip_60_1204", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 300, refId = "item_silverMedal", },}, }, },
	["shop_item_054"] = { refId = "shop_item_054", property = { storeType = "shop_equip", itemId = "equip_60_1303", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 300, refId = "item_silverMedal", },}, }, },
	["shop_item_055"] = { refId = "shop_item_055", property = { storeType = "shop_equip", itemId = "equip_60_6103", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 400, refId = "item_silverMedal", },}, }, },
	["shop_item_056"] = { refId = "shop_item_056", property = { storeType = "shop_equip", itemId = "equip_60_6202", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 400, refId = "item_silverMedal", },}, }, },
	["shop_item_057"] = { refId = "shop_item_057", property = { storeType = "shop_equip", itemId = "equip_60_6301", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 400, refId = "item_silverMedal", },}, }, },
	["shop_item_058"] = { refId = "shop_item_058", property = { storeType = "shop_equip", itemId = "equip_70_1102", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 300, refId = "item_goldMedal", },}, }, },
	["shop_item_059"] = { refId = "shop_item_059", property = { storeType = "shop_equip", itemId = "equip_70_1203", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 300, refId = "item_goldMedal", },}, }, },
	["shop_item_060"] = { refId = "shop_item_060", property = { storeType = "shop_equip", itemId = "equip_70_1302", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 300, refId = "item_goldMedal", },}, }, },
	["shop_item_061"] = { refId = "shop_item_061", property = { storeType = "shop_equip", itemId = "equip_70_1303", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 300, refId = "item_goldMedal", },}, }, },
	["shop_item_062"] = { refId = "shop_item_062", property = { storeType = "shop_equip", itemId = "equip_70_6102", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 200, refId = "item_goldMedal", },}, }, },
	["shop_item_063"] = { refId = "shop_item_063", property = { storeType = "shop_equip", itemId = "equip_70_6203", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 200, refId = "item_goldMedal", },}, }, },
	["shop_item_064"] = { refId = "shop_item_064", property = { storeType = "shop_equip", itemId = "equip_70_2112", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 500, refId = "item_goldMedal", },}, }, },
	["shop_item_065"] = { refId = "shop_item_065", property = { storeType = "shop_equip", itemId = "equip_70_2122", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 500, refId = "item_goldMedal", },}, }, },
	["shop_item_066"] = { refId = "shop_item_066", property = { storeType = "shop_equip", itemId = "equip_70_2211", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 500, refId = "item_goldMedal", },}, }, },
	["shop_item_067"] = { refId = "shop_item_067", property = { storeType = "shop_equip", itemId = "equip_70_2221", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 500, refId = "item_goldMedal", },}, }, },
	["shop_item_068"] = { refId = "shop_item_068", property = { storeType = "shop_equip", itemId = "equip_70_2311", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 500, refId = "item_goldMedal", },}, }, },
	["shop_item_069"] = { refId = "shop_item_069", property = { storeType = "shop_equip", itemId = "equip_70_2321", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 500, refId = "item_goldMedal", },}, }, },
	["shop_item_070"] = { refId = "shop_item_070", property = { storeType = "shop_5", itemId = "item_moveto_1", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 20000, refId = "gold", },}, }, },
	["shop_item_071"] = { refId = "shop_item_071", property = { storeType = "shop_5", itemId = "item_moveto_2", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 30000, refId = "gold", },}, }, },
	["shop_item_072"] = { refId = "shop_item_072", property = { storeType = "shop_5", itemId = "item_moveto_3", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 40000, refId = "gold", },}, }, },
	["shop_item_073"] = { refId = "shop_item_073", property = { storeType = "shop_5", itemId = "item_feixie", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 40000, refId = "gold", },}, }, },
	["shop_item_074"] = { refId = "shop_item_074", property = { storeType = "shop_100", itemId = "item_superluck", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 50, refId = "item_coupon_2", },}, }, },
	["shop_item_075"] = { refId = "shop_item_075", property = { storeType = "shop_100", itemId = "item_goldMedal", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 10, refId = "item_coupon_2", },}, }, },
	["shop_item_076"] = { refId = "shop_item_076", property = { storeType = "shop_100", itemId = "item_silverMedal", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 3, refId = "item_coupon_2", },}, }, },
	["shop_item_077"] = { refId = "shop_item_077", property = { storeType = "shop_100", itemId = "item_copperMedal", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 20, refId = "item_coupon", },}, }, },
	["shop_item_078"] = { refId = "shop_item_078", property = { storeType = "shop_100", itemId = "item_ironMedal", itemLimitType = 0, itemLimitNum = 0, number = 0, bindStatus = 1,},  priceData = {
			 priceData = { { number = 10, refId = "item_coupon", },}, }, }
}
