-- NAME: PayonPalace
-- TIME: 2014.7.2-19:14:35
-- Generated by editor

GameData = GameData or {}
GameData.PayonPalace= {
	["payonPalace_1"] = { refId = "payonPalace_1", sceneRefId = "S070|S071", time = { duration = "14:00:00|18:00:00", preStartTime = 0, preEndTime = 0,}, 
			activityData = {
				{ transfer = 407,
		 consumeitems = { { itemRefId = "item_templetickets", number = "1", },},
		 planshow = { { itemRefId = "item_qianghuashi", number = "1", },{ itemRefId = "item_zuoqiExp", number = "1", },{ itemRefId = "item_suipian_1", number = "1", },{ itemRefId = "item_ironMedal", number = "1", },}, property = { iconId = "payonPalace_1", name = "BOSS神殿",}, 	},
			}}
}
