-- NAME: WorldElite
-- TIME: 2014.6.11-14:39:16
-- Generated by editor

GameData = GameData or {}
GameData.WorldElite= {
	["elite_1"] = { refId = "elite_1", monsterRefId = "monster_28", refreshTime = 2, sceneRefId = "S036",},
	["elite_10"] = { refId = "elite_10", monsterRefId = "monster_43", refreshTime = 3, sceneRefId = "S068",},
	["elite_11"] = { refId = "elite_11", monsterRefId = "monster_7043", refreshTime = 5, sceneRefId = "S040",},
	["elite_12"] = { refId = "elite_12", monsterRefId = "monster_52", refreshTime = 4, sceneRefId = "S041",},
	["elite_13"] = { refId = "elite_13", monsterRefId = "monster_6052", refreshTime = 5, sceneRefId = "S042",},
	["elite_14"] = { refId = "elite_14", monsterRefId = "monster_52", refreshTime = 4, sceneRefId = "S068",},
	["elite_15"] = { refId = "elite_15", monsterRefId = "monster_7051", refreshTime = 5, sceneRefId = "S042",},
	["elite_16"] = { refId = "elite_16", monsterRefId = "monster_51", refreshTime = 5, sceneRefId = "S068",},
	["elite_17"] = { refId = "elite_17", monsterRefId = "monster_55", refreshTime = 4, sceneRefId = "S043",},
	["elite_18"] = { refId = "elite_18", monsterRefId = "monster_7055", refreshTime = 5, sceneRefId = "S044",},
	["elite_19"] = { refId = "elite_19", monsterRefId = "monster_55", refreshTime = 4, sceneRefId = "S069",},
	["elite_2"] = { refId = "elite_2", monsterRefId = "monster_2028", refreshTime = 2, sceneRefId = "S067",},
	["elite_20"] = { refId = "elite_20", monsterRefId = "monster_33", refreshTime = 5, sceneRefId = "S045",},
	["elite_21"] = { refId = "elite_21", monsterRefId = "monster_7033", refreshTime = 5, sceneRefId = "S046",},
	["elite_22"] = { refId = "elite_22", monsterRefId = "monster_33", refreshTime = 5, sceneRefId = "S069",},
	["elite_3"] = { refId = "elite_3", monsterRefId = "monster_29", refreshTime = 2, sceneRefId = "S036",},
	["elite_4"] = { refId = "elite_4", monsterRefId = "monster_2029", refreshTime = 2, sceneRefId = "S067",},
	["elite_5"] = { refId = "elite_5", monsterRefId = "monster_40", refreshTime = 2, sceneRefId = "S034",},
	["elite_6"] = { refId = "elite_6", monsterRefId = "monster_40", refreshTime = 2, sceneRefId = "S037",},
	["elite_7"] = { refId = "elite_7", monsterRefId = "monster_7040", refreshTime = 2, sceneRefId = "S038",},
	["elite_8"] = { refId = "elite_8", monsterRefId = "monster_2040", refreshTime = 2, sceneRefId = "S067",},
	["elite_9"] = { refId = "elite_9", monsterRefId = "monster_43", refreshTime = 3, sceneRefId = "S039",}
}
