-- NAME: PlayerMonster
-- TIME: 2014.6.13-18:9:12
-- Generated by editor

GameData = GameData or {}
GameData.PlayerMonster= {
	["monster_1001"] = { refId = "monster_1001", property = { gender = 1, name = "暴戾战神", weaponId = 4014, wingId = 6002,}, },
	["monster_1002"] = { refId = "monster_1002", property = { gender = 2, name = "暴戾法爷", weaponId = 4015, wingId = 6003,}, },
	["monster_1003"] = { refId = "monster_1003", property = { gender = 1, name = "暴戾道尊", weaponId = 4016, wingId = 6004,}, },
	["monster_1004"] = { refId = "monster_1004", property = { gender = 1, name = "暴戾战神", weaponId = 4014, wingId = 6002,}, },
	["monster_1005"] = { refId = "monster_1005", property = { gender = 2, name = "暴戾法爷", weaponId = 4015, wingId = 6003,}, },
	["monster_1006"] = { refId = "monster_1006", property = { gender = 1, name = "暴戾道尊", weaponId = 4016, wingId = 6004,}, },
	["monster_1007"] = { refId = "monster_1007", property = { gender = 1, name = "战士学徒", weaponId = 4011, wingId = 0,}, },
	["monster_1008"] = { refId = "monster_1008", property = { gender = 1, name = "拦路恶徒", weaponId = 4012, wingId = 0,}, },
	["monster_1009"] = { refId = "monster_1009", property = { gender = 2, name = "精锐道士", weaponId = 4013, wingId = 6000,}, }
}
