-- NAME: CastleWar
-- TIME: 2014.7.10-16:35:52
-- Generated by editor

GameData = GameData or {}
GameData.CastleWar= {
	["castleWar"] = { refId = "castleWar", sceneRefId = "S012", time = { duration = "2014-07-01 20:30:00|2014-07-01 21:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
					["castleWar_1"] = { refId = "castleWar_1", property = { maxStackNumber = 100, gold = 100000, itemId = "item_gongcheng", timesADay = 1, monsterRefId = "monster_8001",},  castleData = { giftRefID = "item_gift_king",
			 applyTimeData = { endTime = "6|23:59:59", startTime = "1|00:00:00", }, 
			 transfer = { instance = { name = "王城副本", targetScene = "S216", tranferInId = 316, }, kickOut = { name = "沙巴克", targetScene = "S009", tranferInId = 15, }, warMap = { name = "皇宫", targetScene = "S012", tranferInId = 42, }, }, },  firstIntervalDays = 2, rangeIntervalDays = 3, openAndEndTime = "20:30:00|21:00:00",	},
			}}
}
