/* DO NOT EDIT THIS FILE - it is machine generated */
#include <string>
#include <jni.h>
/* Header for class com_morningglory_shell_GardeniaLogin */

#ifndef _Included_com_morningglory_shell_GardeniaLogin
#define _Included_com_morningglory_shell_GardeniaLogin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_morningglory_shell_GardeniaLogin
 * Method:    native_getServerList
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_morningglory_shell_GardeniaLogin_native_1getServerList
  (JNIEnv *, jclass);

/*
 * Class:     com_morningglory_shell_GardeniaLogin
 * Method:    native_loginSuccess
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_morningglory_shell_GardeniaLogin_native_1loginSuccess
  (JNIEnv *, jclass);

/*
 * Class:     com_morningglory_shell_GardeniaLogin
 * Method:    native_getSelectServer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_morningglory_shell_GardeniaLogin_native_1getSelectServer
  (JNIEnv *, jclass);

/*
 * Class:     com_morningglory_shell_GardeniaLogin
 * Method:    native_cancelUpdate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_morningglory_shell_GardeniaLogin_native_1cancelUpdate
  (JNIEnv *, jclass);

/*
 * Class:     com_morningglory_shell_GardeniaLogin
 * Method:    native_showWaitView
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_morningglory_shell_GardeniaLogin_native_1showWaitView
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_morningglory_shell_GardeniaLogin
 * Method:    native_hideWaitView
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_morningglory_shell_GardeniaLogin_native_1hideWaitView
  (JNIEnv *, jclass);

/*
 * Class:     com_morningglory_shell_GardeniaLogin
 * Method:    native_getCurrentPlayerInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_morningglory_shell_GardeniaLogin_native_1getCurrentPlayerInfo
  (JNIEnv *, jclass);

/*
 * Class:     com_morningglory_shell_GardeniaLogin
 * Method:    native_disConnectGameServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_morningglory_shell_GardeniaLogin_native_1disConnectGameServer
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_morningglory_shell_GardeniaLogin_native_1onPayState
	(JNIEnv *, jclass, jint, jint);

JNIEXPORT void JNICALL Java_com_morningglory_shell_GardeniaHelper_native_1baiduShareCallback
	(JNIEnv *, jclass, jint, jint);

JNIEXPORT void JNICALL Java_com_morningglory_shell_GardeniaHelper_native_1appUpdateType
	(JNIEnv *, jclass, jint, jint);

JNIEXPORT void JNICALL Java_com_morningglory_shell_GardeniaLogin_native_1excuteLogOutCallBack
	(JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_morningglory_shell_GardeniaLogin_native_1sdkLogout
	(JNIEnv *, jclass, jboolean);

void jni_getSrvListSuccess(const char* str);

// 读取android的配置数据 -- BEGIN
std::string jni_getLoginSettingUrl();

std::string jni_getBackupSettingUrl();

std::string jni_getBridgeUrl();

std::string jni_getQDKey();

std::string jni_getGameKey();

int jni_getQDCode1();

int jni_getQDCode2();

std::string jni_getUUid();

std::string jni_getPlatform();  //获取平台

std::string jni_getSuffix(); //获取安装包的后缀名
// 读取android的配置数据 -- END

bool jni_isAccountManager();

void jni_showAccountManager();

void jni_selectServerId(int serverId);

void jni_loginError(int errCode);

void jni_openPay(char* rechargeChannelJson, int handler);

void jni_bridgeAuthSuccess(const char* response);

void jni_submitExtendData(const char* extendData);

std::string jni_getAuthData();

bool jni_needShowUserCenter();

void jni_showUserCenter();

void jni_logout();

bool jni_needShowCustomTopupView();

#ifdef __cplusplus
}
#endif
#endif
