-- NAME: Adornmentnpc
-- TIME: 2014.3.11-20:12:21
-- Generated by editor

GameData = GameData or {}
GameData.Adornmentnpc= {
	["adornmentnpc_1"] = { refId = "adornmentnpc_1", property = { name = "四处飞舞蝴蝶", modelId = 8002,}, },
	["adornmentnpc_2"] = { refId = "adornmentnpc_2", property = { name = "原地飞舞蝴蝶", modelId = 8003,}, },
	["adornmentnpc_3"] = { refId = "adornmentnpc_3", property = { name = "原地不动蝴蝶", modelId = 8004,}, },
	["adornmentnpc_4"] = { refId = "adornmentnpc_4", property = { name = "窄水波", modelId = 8005,}, },
	["adornmentnpc_5"] = { refId = "adornmentnpc_5", property = { name = "宽水波", modelId = 8006,}, },
	["adornmentnpc_6"] = { refId = "adornmentnpc_6", property = { name = "大量落叶", modelId = 8007,}, },
	["adornmentnpc_7"] = { refId = "adornmentnpc_7", property = { name = "单片落叶", modelId = 8008,}, },
	["adornmentnpc_8"] = { refId = "adornmentnpc_8", property = { name = "光束", modelId = 8009,}, },
	["adornmentnpc_9"] = { refId = "adornmentnpc_9", property = { name = "火焰", modelId = 8010,}, }
}
