-- NAME: PlayerNpc
-- TIME: 2014.7.23-22:27:34
-- Generated by editor

GameData = GameData or {}
GameData.PlayerNpc= {
	["npc_ride"] = { refId = "npc_ride", property = { gender = 1, weaponModleId = 0, wingModleId = 0, rideModleId = 5007, standTurn = 6,}, },
	["npc_wing"] = { refId = "npc_wing", property = { gender = 2, weaponModleId = 4056, wingModleId = 6008, rideModleId = 0, standTurn = 4,}, }
}
