-- NAME: HandUpSkill
-- TIME: 2014.4.29-17:26:48
-- Generated by editor

GameData = GameData or {}
GameData.HandUpSkill= {
	["skill_ds_1"] = { refId = "skill_ds_1", property = { professionId = 3, targetNum = 2, priority = 12, buffRefId = "buff_skill_4",}, },
	["skill_ds_11"] = { refId = "skill_ds_11", property = { professionId = 3, targetNum = 2, priority = 16, buffRefId = "0",}, },
	["skill_ds_3"] = { refId = "skill_ds_3", property = { professionId = 3, targetNum = 2, priority = 13, buffRefId = "buff_skill_5",}, },
	["skill_ds_4"] = { refId = "skill_ds_4", property = { professionId = 3, targetNum = 0, priority = 14, buffRefId = "0",}, },
	["skill_ds_5"] = { refId = "skill_ds_5", property = { professionId = 3, targetNum = 2, priority = 15, buffRefId = "0",}, },
	["skill_fs_1"] = { refId = "skill_fs_1", property = { professionId = 2, targetNum = 0, priority = 4, buffRefId = "0",}, },
	["skill_fs_10"] = { refId = "skill_fs_10", property = { professionId = 2, targetNum = 1, priority = 8, buffRefId = "0",}, },
	["skill_fs_11"] = { refId = "skill_fs_11", property = { professionId = 2, targetNum = 2, priority = 11, buffRefId = "buff_skill_3",}, },
	["skill_fs_12"] = { refId = "skill_fs_12", property = { professionId = 2, targetNum = 1, priority = 10, buffRefId = "0",}, },
	["skill_fs_4"] = { refId = "skill_fs_4", property = { professionId = 2, targetNum = 0, priority = 5, buffRefId = "0",}, },
	["skill_fs_6"] = { refId = "skill_fs_6", property = { professionId = 2, targetNum = 0, priority = 6, buffRefId = "0",}, },
	["skill_fs_7"] = { refId = "skill_fs_7", property = { professionId = 2, targetNum = 1, priority = 7, buffRefId = "0",}, },
	["skill_zs_3"] = { refId = "skill_zs_3", property = { professionId = 1, targetNum = 2, priority = 1, buffRefId = "0",}, },
	["skill_zs_4"] = { refId = "skill_zs_4", property = { professionId = 1, targetNum = 2, priority = 2, buffRefId = "0",}, },
	["skill_zs_6"] = { refId = "skill_zs_6", property = { professionId = 1, targetNum = 2, priority = 3, buffRefId = "0",}, }
}
