-- NAME: NewGuidelines
-- TIME: 2014.8.6-11:37:34
-- Generated by editor

GameData = GameData or {}
GameData.NewGuidelines= {
	["quest_39"] = { refId = "quest_39", stepfirst = 47, property = { tips = "引导打开活动面板",}, },
	["quest_40"] = { refId = "quest_40", stepfirst = 64, property = { tips = "爵位解锁指引",}, },
	["quest_5"] = { refId = "quest_5", stepfirst = 36, property = { tips = "点击使用小魔血左上角头像指引",}, },
	["quest_56"] = { refId = "quest_56", stepfirst = 42, property = { tips = "点击副本图标指引",}, },
	["quest_63"] = { refId = "quest_63", stepfirst = 61, property = { tips = "坐骑升级指引",}, },
	["quest_77"] = { refId = "quest_77", stepfirst = 63, property = { tips = "翅膀升级指引",}, }
}
