-- NAME: Discount
-- TIME: 2014.6.30-14:46:7
-- Generated by editor

GameData = GameData or {}
GameData.Discount= {
	["discount_item"] = { refId = "discount_item", name = "打折道具",
			configData = {
					["discount_batch1_1"] = { refId = "discount_batch1_1", discountData = { itemId = "item_chibangExp", bindStatus = 1, OriginalsaleCurrency = 1, OriginalsalePrice = 40, saleCurrency = 2, salePrice = 200000, itemLimitNum = 999, privateLimitNum = 10,}, 	},
					["discount_batch1_2"] = { refId = "discount_batch1_2", discountData = { itemId = "item_qianghuashi", bindStatus = 1, OriginalsaleCurrency = 1, OriginalsalePrice = 40, saleCurrency = 2, salePrice = 200000, itemLimitNum = 999, privateLimitNum = 10,}, 	},
					["discount_batch1_3"] = { refId = "discount_batch1_3", discountData = { itemId = "item_zuoqiExp", bindStatus = 1, OriginalsaleCurrency = 1, OriginalsalePrice = 40, saleCurrency = 2, salePrice = 200000, itemLimitNum = 999, privateLimitNum = 10,}, 	},
					["discount_batch1_4"] = { refId = "discount_batch1_4", discountData = { itemId = "item_shenqiExp", bindStatus = 1, OriginalsaleCurrency = 1, OriginalsalePrice = 80, saleCurrency = 2, salePrice = 400000, itemLimitNum = 999, privateLimitNum = 10,}, 	},
					["discount_batch2_1"] = { refId = "discount_batch2_1", discountData = { itemId = "item_moxueshi_1", bindStatus = 1, OriginalsaleCurrency = 1, OriginalsalePrice = 800, saleCurrency = 2, salePrice = 1000000, itemLimitNum = 100, privateLimitNum = 2,}, 	},
					["discount_batch2_2"] = { refId = "discount_batch2_2", discountData = { itemId = "item_3exp", bindStatus = 1, OriginalsaleCurrency = 1, OriginalsalePrice = 376, saleCurrency = 2, salePrice = 1880000, itemLimitNum = 200, privateLimitNum = 5,}, 	},
					["discount_batch2_3"] = { refId = "discount_batch2_3", discountData = { itemId = "item_zhenmoling_1", bindStatus = 1, OriginalsaleCurrency = 1, OriginalsalePrice = 20, saleCurrency = 2, salePrice = 100000, itemLimitNum = 999, privateLimitNum = 20,}, 	},
					["discount_batch3_1"] = { refId = "discount_batch3_1", discountData = { itemId = "item_danyao_1", bindStatus = 1, OriginalsaleCurrency = 1, OriginalsalePrice = 400, saleCurrency = 2, salePrice = 2000000, itemLimitNum = 200, privateLimitNum = 5,}, 	},
					["discount_batch3_2"] = { refId = "discount_batch3_2", discountData = { itemId = "item_danyao_2", bindStatus = 1, OriginalsaleCurrency = 1, OriginalsalePrice = 400, saleCurrency = 2, salePrice = 2000000, itemLimitNum = 200, privateLimitNum = 5,}, 	},
					["discount_batch3_3"] = { refId = "discount_batch3_3", discountData = { itemId = "item_danyao_3", bindStatus = 1, OriginalsaleCurrency = 1, OriginalsalePrice = 400, saleCurrency = 2, salePrice = 2000000, itemLimitNum = 200, privateLimitNum = 5,}, 	},
					["discount_batch3_4"] = { refId = "discount_batch3_4", discountData = { itemId = "item_danyao_4", bindStatus = 1, OriginalsaleCurrency = 1, OriginalsalePrice = 400, saleCurrency = 2, salePrice = 2000000, itemLimitNum = 200, privateLimitNum = 5,}, 	},
					["discount_batch3_5"] = { refId = "discount_batch3_5", discountData = { itemId = "item_danyao_5", bindStatus = 1, OriginalsaleCurrency = 1, OriginalsalePrice = 400, saleCurrency = 2, salePrice = 2000000, itemLimitNum = 200, privateLimitNum = 5,}, 	},
			}}
}
