-- NAME: LimitTimeRank
-- TIME: 2014.6.26-14:53:9
-- Generated by editor

GameData = GameData or {}
GameData.LimitTimeRank= {
	["limitTimeRank_1_1"] = { refId = "limitTimeRank_1_1", rankType = 1, rankInterval = "1-1", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 150, itemRefId = "item_goldMedal", },{ bindStatus = 1, itemCount = 1, itemRefId = "item_superluck", },}, relatedType = 0, }, propertyReward = { unbindedGold = 50000, }, }, }, },
	["limitTimeRank_1_2"] = { refId = "limitTimeRank_1_2", rankType = 1, rankInterval = "2-2", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 200, itemRefId = "item_silverMedal", },{ bindStatus = 1, itemCount = 1, itemRefId = "item_superluck", },}, relatedType = 0, }, propertyReward = { unbindedGold = 30000, }, }, }, },
	["limitTimeRank_1_3"] = { refId = "limitTimeRank_1_3", rankType = 1, rankInterval = "3-3", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 90, itemRefId = "item_copperMedal", },{ bindStatus = 1, itemCount = 30, itemRefId = "item_luck", },}, relatedType = 0, }, propertyReward = { unbindedGold = 10000, }, }, }, },
	["limitTimeRank_1_4"] = { refId = "limitTimeRank_1_4", rankType = 1, rankInterval = "4-10", rankReward = {
			 rankReward = { propertyReward = { unbindedGold = 5000, }, }, }, },
	["limitTimeRank_1_5"] = { refId = "limitTimeRank_1_5", rankType = 1, rankInterval = "11-20", rankReward = {
			 rankReward = { propertyReward = { unbindedGold = 1000, }, }, }, },
	["limitTimeRank_2_1"] = { refId = "limitTimeRank_2_1", rankType = 2, rankInterval = "1-1", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 1000, itemRefId = "item_chibangExp", },{ bindStatus = 1, itemCount = 10, itemRefId = "item_duihuanquan_2", },}, relatedType = 0, }, propertyReward = { unbindedGold = 20000, }, }, }, },
	["limitTimeRank_2_2"] = { refId = "limitTimeRank_2_2", rankType = 2, rankInterval = "2-2", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 600, itemRefId = "item_chibangExp", },{ bindStatus = 1, itemCount = 8, itemRefId = "item_duihuanquan_2", },}, relatedType = 0, }, propertyReward = { unbindedGold = 10000, }, }, }, },
	["limitTimeRank_2_3"] = { refId = "limitTimeRank_2_3", rankType = 2, rankInterval = "3-3", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 300, itemRefId = "item_chibangExp", },{ bindStatus = 1, itemCount = 3, itemRefId = "item_duihuanquan_2", },}, relatedType = 0, }, propertyReward = { unbindedGold = 5000, }, }, }, },
	["limitTimeRank_2_4"] = { refId = "limitTimeRank_2_4", rankType = 2, rankInterval = "4-10", rankReward = {
			 rankReward = { propertyReward = { unbindedGold = 3000, }, }, }, },
	["limitTimeRank_2_5"] = { refId = "limitTimeRank_2_5", rankType = 2, rankInterval = "11-20", rankReward = {
			 rankReward = { propertyReward = { unbindedGold = 300, }, }, }, },
	["limitTimeRank_3_1"] = { refId = "limitTimeRank_3_1", rankType = 3, rankInterval = "1-1", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 20, itemRefId = "item_goldMedal", },{ bindStatus = 1, itemCount = 200, itemRefId = "item_qianghuashi", },}, relatedType = 0, }, propertyReward = { unbindedGold = 10000, }, }, }, },
	["limitTimeRank_3_2"] = { refId = "limitTimeRank_3_2", rankType = 3, rankInterval = "2-2", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 20, itemRefId = "item_silverMedal", },{ bindStatus = 1, itemCount = 200, itemRefId = "item_qianghuashi", },}, relatedType = 0, }, propertyReward = { unbindedGold = 5000, }, }, }, },
	["limitTimeRank_3_3"] = { refId = "limitTimeRank_3_3", rankType = 3, rankInterval = "3-3", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 10, itemRefId = "item_silverMedal", },{ bindStatus = 1, itemCount = 200, itemRefId = "item_qianghuashi", },}, relatedType = 0, }, propertyReward = { unbindedGold = 2000, }, }, }, },
	["limitTimeRank_3_4"] = { refId = "limitTimeRank_3_4", rankType = 3, rankInterval = "4-10", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 100, itemRefId = "item_qianghuashi", },}, relatedType = 0, }, propertyReward = { unbindedGold = 1000, }, }, }, },
	["limitTimeRank_3_5"] = { refId = "limitTimeRank_3_5", rankType = 3, rankInterval = "11-20", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 100, itemRefId = "item_qianghuashi", },}, relatedType = 0, }, propertyReward = { unbindedGold = 500, }, }, }, },
	["limitTimeRank_4_1"] = { refId = "limitTimeRank_4_1", rankType = 4, rankInterval = "1-1", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 20, itemRefId = "item_goldMedal", },{ bindStatus = 1, itemCount = 200, itemRefId = "item_qianghuashi", },}, relatedType = 0, }, propertyReward = { unbindedGold = 10000, }, }, }, },
	["limitTimeRank_4_2"] = { refId = "limitTimeRank_4_2", rankType = 4, rankInterval = "2-2", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 20, itemRefId = "item_silverMedal", },{ bindStatus = 1, itemCount = 200, itemRefId = "item_qianghuashi", },}, relatedType = 0, }, propertyReward = { unbindedGold = 5000, }, }, }, },
	["limitTimeRank_4_3"] = { refId = "limitTimeRank_4_3", rankType = 4, rankInterval = "3-3", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 10, itemRefId = "item_silverMedal", },{ bindStatus = 1, itemCount = 200, itemRefId = "item_qianghuashi", },}, relatedType = 0, }, propertyReward = { unbindedGold = 2000, }, }, }, },
	["limitTimeRank_4_4"] = { refId = "limitTimeRank_4_4", rankType = 4, rankInterval = "4-10", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 100, itemRefId = "item_qianghuashi", },}, relatedType = 0, }, propertyReward = { unbindedGold = 1000, }, }, }, },
	["limitTimeRank_4_5"] = { refId = "limitTimeRank_4_5", rankType = 4, rankInterval = "11-20", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 100, itemRefId = "item_qianghuashi", },}, relatedType = 0, }, propertyReward = { unbindedGold = 500, }, }, }, },
	["limitTimeRank_5_1"] = { refId = "limitTimeRank_5_1", rankType = 5, rankInterval = "1-1", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 1000, itemRefId = "item_zuoqiExp", },}, relatedType = 0, }, propertyReward = { unbindedGold = 30000, }, }, }, },
	["limitTimeRank_5_2"] = { refId = "limitTimeRank_5_2", rankType = 5, rankInterval = "2-2", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 800, itemRefId = "item_zuoqiExp", },}, relatedType = 0, }, propertyReward = { unbindedGold = 10000, }, }, }, },
	["limitTimeRank_5_3"] = { refId = "limitTimeRank_5_3", rankType = 5, rankInterval = "3-3", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 300, itemRefId = "item_zuoqiExp", },}, relatedType = 0, }, propertyReward = { unbindedGold = 8000, }, }, }, },
	["limitTimeRank_5_4"] = { refId = "limitTimeRank_5_4", rankType = 5, rankInterval = "4-10", rankReward = {
			 rankReward = { propertyReward = { unbindedGold = 4000, }, }, }, },
	["limitTimeRank_5_5"] = { refId = "limitTimeRank_5_5", rankType = 5, rankInterval = "11-20", rankReward = {
			 rankReward = { propertyReward = { unbindedGold = 500, }, }, }, },
	["limitTimeRank_6_1"] = { refId = "limitTimeRank_6_1", rankType = 6, rankInterval = "1-1", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 70, itemRefId = "item_suipian_9", },{ bindStatus = 1, itemCount = 1000, itemRefId = "item_shenqiExp", },}, relatedType = 0, }, propertyReward = { unbindedGold = 30000, }, }, }, },
	["limitTimeRank_6_2"] = { refId = "limitTimeRank_6_2", rankType = 6, rankInterval = "2-2", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 50, itemRefId = "item_suipian_8", },{ bindStatus = 1, itemCount = 800, itemRefId = "item_shenqiExp", },}, relatedType = 0, }, propertyReward = { unbindedGold = 10000, }, }, }, },
	["limitTimeRank_6_3"] = { refId = "limitTimeRank_6_3", rankType = 6, rankInterval = "3-3", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 25, itemRefId = "item_suipian_7", },{ bindStatus = 1, itemCount = 400, itemRefId = "item_shenqiExp", },}, relatedType = 0, }, propertyReward = { unbindedGold = 8000, }, }, }, },
	["limitTimeRank_6_4"] = { refId = "limitTimeRank_6_4", rankType = 6, rankInterval = "4-10", rankReward = {
			 rankReward = { propertyReward = { unbindedGold = 4000, }, }, }, },
	["limitTimeRank_6_5"] = { refId = "limitTimeRank_6_5", rankType = 6, rankInterval = "11-20", rankReward = {
			 rankReward = { propertyReward = { unbindedGold = 500, }, }, }, },
	["limitTimeRank_7_1"] = { refId = "limitTimeRank_7_1", rankType = 7, rankInterval = "1-1", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 20, itemRefId = "item_goldMedal", },{ bindStatus = 1, itemCount = 200, itemRefId = "item_qianghuashi", },}, relatedType = 0, }, propertyReward = { unbindedGold = 10000, }, }, }, },
	["limitTimeRank_7_2"] = { refId = "limitTimeRank_7_2", rankType = 7, rankInterval = "2-2", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 20, itemRefId = "item_silverMedal", },{ bindStatus = 1, itemCount = 200, itemRefId = "item_qianghuashi", },}, relatedType = 0, }, propertyReward = { unbindedGold = 5000, }, }, }, },
	["limitTimeRank_7_3"] = { refId = "limitTimeRank_7_3", rankType = 7, rankInterval = "3-3", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 10, itemRefId = "item_silverMedal", },{ bindStatus = 1, itemCount = 200, itemRefId = "item_qianghuashi", },}, relatedType = 0, }, propertyReward = { unbindedGold = 2000, }, }, }, },
	["limitTimeRank_7_4"] = { refId = "limitTimeRank_7_4", rankType = 7, rankInterval = "4-10", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 100, itemRefId = "item_qianghuashi", },}, relatedType = 0, }, propertyReward = { unbindedGold = 1000, }, }, }, },
	["limitTimeRank_7_5"] = { refId = "limitTimeRank_7_5", rankType = 7, rankInterval = "11-20", rankReward = {
			 rankReward = { itemReward = { itemList = { { bindStatus = 1, itemCount = 100, itemRefId = "item_qianghuashi", },}, relatedType = 0, }, propertyReward = { unbindedGold = 500, }, }, }, }
}
