-- NAME: Mining
-- TIME: 2014.7.24-11:42:27
-- Generated by editor

GameData = GameData or {}
GameData.Mining= {
	["sa_1"] = { refId = "sa_1", sceneRefId = "S217", time = { duration = "11:00:00|11:30:00&15:30:00|16:00:00", preStartTime = 600, preEndTime = 300,}, 
			activityData = {
				{ limitCount = 20, limitLevel = 40,	},
			}}
}
