-- NAME: MonsterInvasionScroll
-- TIME: 2014.6.23-21:24:29
-- Generated by editor

GameData = GameData or {}
GameData.MonsterInvasionScroll= {
	["monsterInvasionScroll_1"] = { refId = "monsterInvasionScroll_1", stage = 1, range = "1|30", property = { tips = "你看不见我的兑换券！",}, },
	["monsterInvasionScroll_2"] = { refId = "monsterInvasionScroll_2", stage = 2, range = "31|200", property = { tips = "有兑换券，抢他！",}, },
	["monsterInvasionScroll_3"] = { refId = "monsterInvasionScroll_3", stage = 3, range = "201", property = { tips = "兑换券土豪！",}, }
}
