-- NAME: MonsterInvasion
-- TIME: 2014.7.24-14:30:34
-- Generated by editor

GameData = GameData or {}
GameData.MonsterInvasion= {
	["monsterInvasion1"] = { refId = "monsterInvasion1", sceneRefId = "S218", time = { duration = "12:00:00|12:30:00&20:00:00|20:30:00", preStartTime = 300, preEndTime = 300,}, 
			activityData = {
					["monsterInvasion1"] = { refId = "monsterInvasion1", property = { level = 40, expMultiple = 0,}, 
		 contantItem = { "item_coupon_2", "item_coupon", },
		 contantScene = { "S218", "S219", },	},
			}},
	["monsterInvasion2"] = { refId = "monsterInvasion2", sceneRefId = "S219", time = { duration = "12:00:00|12:30:00&20:00:00|20:30:00", preStartTime = 300, preEndTime = 300,}, 
			activityData = {
					["monsterInvasion2"] = { refId = "monsterInvasion2", property = { level = 40, expMultiple = 0,}, 
		 contantItem = { "item_coupon_2", "item_coupon", },
		 contantScene = { "S218", "S219", },	},
			}}
}
