-- NAME: MultiExp
-- TIME: 2014.7.24-14:30:35
-- Generated by editor

GameData = GameData or {}
GameData.MultiExp= {
	["multiExp"] = { refId = "multiExp", sceneRefId = "Sall", time = { duration = "16:30:00|18:00:00", preStartTime = 0, preEndTime = 0,}, 
			activityData = {
				{ expMultiple = 2,	},
			}}
}
