-- NAME: Online
-- TIME: 2014.7.9-1:43:54
-- Generated by editor

GameData = GameData or {}
GameData.Online= {
	["online_1"] = { refId = "online_1", property = { onlineSecond = 120, onlinePreRefId = "", onlineNextRefId = "online_2",},  onlineReward = {
			 AccumulateonlineReward = { { bindStatus = 1, number = 10, refId = "item_drug_1", },{ bindStatus = 1, number = 10, refId = "item_drug_4", },{ bindStatus = 1, number = 10, refId = "item_zhenmoling_1", },}, }, },
	["online_2"] = { refId = "online_2", property = { onlineSecond = 600, onlinePreRefId = "online_1", onlineNextRefId = "online_3",},  onlineReward = {
			 AccumulateonlineReward = { { bindStatus = 1, number = 20, refId = "item_drug_1", },{ bindStatus = 1, number = 20, refId = "item_drug_4", },{ bindStatus = 1, number = 20, refId = "item_zhenmoling_1", },}, }, },
	["online_3"] = { refId = "online_3", property = { onlineSecond = 1800, onlinePreRefId = "online_2", onlineNextRefId = "online_4",},  onlineReward = {
			 AccumulateonlineReward = { { bindStatus = 1, number = 12, refId = "item_drug_7", },{ bindStatus = 1, number = 40, refId = "item_zhenmoling_1", },}, }, },
	["online_4"] = { refId = "online_4", property = { onlineSecond = 3600, onlinePreRefId = "online_3", onlineNextRefId = "",},  onlineReward = {
			 AccumulateonlineReward = { { bindStatus = 1, number = 1, refId = "item_duihuanquan_1", },{ bindStatus = 1, number = 6, refId = "item_drug_8", },{ bindStatus = 1, number = 80, refId = "item_zhenmoling_1", },}, }, }
}
