-- NAME: RankBeginEndTime
-- TIME: 2014.6.17-13:52:37
-- Generated by editor

GameData = GameData or {}
GameData.RankBeginEndTime= {
	["rankBeginEndTime_1"] = { refId = "rankBeginEndTime_1", rankType = 1, beginTime = "00:00:00", endTime = "49:00:00",},
	["rankBeginEndTime_2"] = { refId = "rankBeginEndTime_2", rankType = 2, beginTime = "00:00:00", endTime = "49:00:00",},
	["rankBeginEndTime_3"] = { refId = "rankBeginEndTime_3", rankType = 3, beginTime = "00:00:00", endTime = "49:00:00",},
	["rankBeginEndTime_4"] = { refId = "rankBeginEndTime_4", rankType = 4, beginTime = "00:00:00", endTime = "49:00:00",},
	["rankBeginEndTime_5"] = { refId = "rankBeginEndTime_5", rankType = 5, beginTime = "00:00:00", endTime = "49:00:00",},
	["rankBeginEndTime_6"] = { refId = "rankBeginEndTime_6", rankType = 6, beginTime = "00:00:00", endTime = "49:00:00",},
	["rankBeginEndTime_7"] = { refId = "rankBeginEndTime_7", rankType = 7, beginTime = "00:00:00", endTime = "49:00:00",}
}
