-- NAME: ResDownload
-- TIME: 2014.6.23-11:41:53
-- Generated by editor

GameData = GameData or {}
GameData.ResDownload= {
	["extend.zpk"] = { refId = "extend.zpk",
		 reward = { { bindStatus = "1", number = 1, refId = "item_2exp", },{ bindStatus = "1", number = 10, refId = "item_qianghuashi", },{ bindStatus = "1", number = 200000, refId = "gold", },},}
}
