-- NAME: Sign
-- TIME: 2014.6.30-12:20:5
-- Generated by editor

GameData = GameData or {}
GameData.Sign= {
	["sign_1"] = { refId = "sign_1", property = { signCount = 1,},  signData = {
			 rewardField = { itemReward = { itemList = { { bindStatus = 1, itemCount = 12, itemRefId = "item_drug_7", },{ bindStatus = 1, itemCount = 5, itemRefId = "item_qianghuashi", },}, relatedType = 0, }, }, }, },
	["sign_2"] = { refId = "sign_2", property = { signCount = 2,},  signData = {
			 rewardField = { itemReward = { itemList = { { bindStatus = 1, itemCount = 3, itemRefId = "item_duihuanquan_1", },{ bindStatus = 1, itemCount = 10, itemRefId = "item_qianghuashi", },}, relatedType = 0, }, }, }, },
	["sign_3"] = { refId = "sign_3", property = { signCount = 5,},  signData = {
			 rewardField = { itemReward = { itemList = { { bindStatus = 1, itemCount = 10, itemRefId = "item_duihuanquan_1", },{ bindStatus = 1, itemCount = 20, itemRefId = "item_qianghuashi", },}, relatedType = 0, }, }, }, },
	["sign_4"] = { refId = "sign_4", property = { signCount = 15,},  signData = {
			 rewardField = { itemReward = { itemList = { { bindStatus = 1, itemCount = 1, itemRefId = "item_moxueshi_1", },{ bindStatus = 1, itemCount = 50, itemRefId = "item_qianghuashi", },}, relatedType = 0, }, propertyReward = { bindedGold = 5000, }, }, }, },
	["sign_5"] = { refId = "sign_5", property = { signCount = 25,},  signData = {
			 rewardField = { itemReward = { itemList = { { bindStatus = 1, itemCount = 10, itemRefId = "item_goldMedal", },{ bindStatus = 1, itemCount = 100, itemRefId = "item_qianghuashi", },{ bindStatus = 1, itemCount = 9, itemRefId = "item_giftcard", },}, relatedType = 0, }, }, }, }
}
