-- NAME: TeamBoss
-- TIME: 2014.6.12-17:10:28
-- Generated by editor

GameData = GameData or {}
GameData.TeamBoss= {
	["teamBoss_111"] = { refId = "teamBoss_111", sceneRefId = "S035", time = { duration = "13:00:00|14:30:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 1,
		 transfer = { transferIn = { targetScene = "S035", tranferInId = 26, }, transferOut = { targetScene = "S036", tranferOutId = 69, }, },
		 contentScene = { { targetScene = "S053", },{ targetScene = "S054", },}, BossRefId = "",	},
			}},
	["teamBoss_112"] = { refId = "teamBoss_112", sceneRefId = "S036", time = { duration = "13:00:00|14:30:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 1,
		 transfer = { transferIn = { targetScene = "S036", tranferInId = 28, }, transferOut = { targetScene = "S036", tranferOutId = 69, }, },
		 contentScene = { { targetScene = "S053", },{ targetScene = "S054", },}, BossRefId = "",	},
			}},
	["teamBoss_113"] = { refId = "teamBoss_113", sceneRefId = "S053", time = { duration = "13:00:00|14:30:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 1,
		 transfer = { transferIn = { targetScene = "S053", tranferInId = 70, }, transferOut = { targetScene = "S036", tranferOutId = 69, }, },
		 contentScene = { { targetScene = "S053", },{ targetScene = "S054", },}, BossRefId = "monster_6030",	},
			}},
	["teamBoss_114"] = { refId = "teamBoss_114", sceneRefId = "S054", time = { duration = "13:00:00|14:30:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 1,
		 transfer = { transferIn = { targetScene = "S054", tranferInId = 72, }, transferOut = { targetScene = "S036", tranferOutId = 69, }, },
		 contentScene = { { targetScene = "S053", },{ targetScene = "S054", },}, BossRefId = "monster_7030",	},
			}},
	["teamBoss_121"] = { refId = "teamBoss_121", sceneRefId = "S045", time = { duration = "13:00:00|14:30:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 1,
		 transfer = { transferIn = { targetScene = "S045", tranferInId = 44, }, transferOut = { targetScene = "S046", tranferOutId = 89, }, },
		 contentScene = { { targetScene = "S063", },{ targetScene = "S064", },}, BossRefId = "",	},
			}},
	["teamBoss_122"] = { refId = "teamBoss_122", sceneRefId = "S046", time = { duration = "13:00:00|14:30:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 1,
		 transfer = { transferIn = { targetScene = "S046", tranferInId = 46, }, transferOut = { targetScene = "S046", tranferOutId = 89, }, },
		 contentScene = { { targetScene = "S063", },{ targetScene = "S064", },}, BossRefId = "",	},
			}},
	["teamBoss_123"] = { refId = "teamBoss_123", sceneRefId = "S063", time = { duration = "13:00:00|14:30:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 1,
		 transfer = { transferIn = { targetScene = "S063", tranferInId = 90, }, transferOut = { targetScene = "S046", tranferOutId = 89, }, },
		 contentScene = { { targetScene = "S063", },{ targetScene = "S064", },}, BossRefId = "monster_6034",	},
			}},
	["teamBoss_124"] = { refId = "teamBoss_124", sceneRefId = "S064", time = { duration = "13:00:00|14:30:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 1,
		 transfer = { transferIn = { targetScene = "S064", tranferInId = 92, }, transferOut = { targetScene = "S046", tranferOutId = 89, }, },
		 contentScene = { { targetScene = "S063", },{ targetScene = "S064", },}, BossRefId = "monster_7034",	},
			}},
	["teamBoss_211"] = { refId = "teamBoss_211", sceneRefId = "S031", time = { duration = "17:00:00|18:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 2,
		 transfer = { transferIn = { targetScene = "S031", tranferInId = 18, }, transferOut = { targetScene = "S032", tranferOutId = 61, }, },
		 contentScene = { { targetScene = "S049", },{ targetScene = "S050", },}, BossRefId = "",	},
			}},
	["teamBoss_212"] = { refId = "teamBoss_212", sceneRefId = "S032", time = { duration = "17:00:00|18:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 2,
		 transfer = { transferIn = { targetScene = "S032", tranferInId = 20, }, transferOut = { targetScene = "S032", tranferOutId = 61, }, },
		 contentScene = { { targetScene = "S049", },{ targetScene = "S050", },}, BossRefId = "",	},
			}},
	["teamBoss_213"] = { refId = "teamBoss_213", sceneRefId = "S049", time = { duration = "17:00:00|18:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 2,
		 transfer = { transferIn = { targetScene = "S049", tranferInId = 62, }, transferOut = { targetScene = "S032", tranferOutId = 61, }, },
		 contentScene = { { targetScene = "S049", },{ targetScene = "S050", },}, BossRefId = "monster_6020",	},
			}},
	["teamBoss_214"] = { refId = "teamBoss_214", sceneRefId = "S050", time = { duration = "17:00:00|18:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 2,
		 transfer = { transferIn = { targetScene = "S050", tranferInId = 64, }, transferOut = { targetScene = "S032", tranferOutId = 61, }, },
		 contentScene = { { targetScene = "S049", },{ targetScene = "S050", },}, BossRefId = "monster_7020",	},
			}},
	["teamBoss_221"] = { refId = "teamBoss_221", sceneRefId = "S041", time = { duration = "17:00:00|18:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 2,
		 transfer = { transferIn = { targetScene = "S041", tranferInId = 38, }, transferOut = { targetScene = "S042", tranferOutId = 81, }, },
		 contentScene = { { targetScene = "S059", },{ targetScene = "S060", },}, BossRefId = "",	},
			}},
	["teamBoss_222"] = { refId = "teamBoss_222", sceneRefId = "S042", time = { duration = "17:00:00|18:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 2,
		 transfer = { transferIn = { targetScene = "S042", tranferInId = 40, }, transferOut = { targetScene = "S042", tranferOutId = 81, }, },
		 contentScene = { { targetScene = "S059", },{ targetScene = "S060", },}, BossRefId = "",	},
			}},
	["teamBoss_223"] = { refId = "teamBoss_223", sceneRefId = "S059", time = { duration = "17:00:00|18:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 2,
		 transfer = { transferIn = { targetScene = "S059", tranferInId = 82, }, transferOut = { targetScene = "S042", tranferOutId = 81, }, },
		 contentScene = { { targetScene = "S059", },{ targetScene = "S060", },}, BossRefId = "monster_6053",	},
			}},
	["teamBoss_224"] = { refId = "teamBoss_224", sceneRefId = "S060", time = { duration = "17:00:00|18:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 2,
		 transfer = { transferIn = { targetScene = "S060", tranferInId = 84, }, transferOut = { targetScene = "S042", tranferOutId = 81, }, },
		 contentScene = { { targetScene = "S059", },{ targetScene = "S060", },}, BossRefId = "monster_7053",	},
			}},
	["teamBoss_231"] = { refId = "teamBoss_231", sceneRefId = "S039", time = { duration = "17:00:00|18:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 2,
		 transfer = { transferIn = { targetScene = "S039", tranferInId = 34, }, transferOut = { targetScene = "S040", tranferOutId = 77, }, },
		 contentScene = { { targetScene = "S057", },{ targetScene = "S058", },}, BossRefId = "",	},
			}},
	["teamBoss_232"] = { refId = "teamBoss_232", sceneRefId = "S040", time = { duration = "17:00:00|18:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 2,
		 transfer = { transferIn = { targetScene = "S040", tranferInId = 36, }, transferOut = { targetScene = "S040", tranferOutId = 77, }, },
		 contentScene = { { targetScene = "S057", },{ targetScene = "S058", },}, BossRefId = "",	},
			}},
	["teamBoss_233"] = { refId = "teamBoss_233", sceneRefId = "S057", time = { duration = "17:00:00|18:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 2,
		 transfer = { transferIn = { targetScene = "S057", tranferInId = 78, }, transferOut = { targetScene = "S040", tranferOutId = 77, }, },
		 contentScene = { { targetScene = "S057", },{ targetScene = "S058", },}, BossRefId = "monster_6045",	},
			}},
	["teamBoss_234"] = { refId = "teamBoss_234", sceneRefId = "S058", time = { duration = "17:00:00|18:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 2,
		 transfer = { transferIn = { targetScene = "S058", tranferInId = 80, }, transferOut = { targetScene = "S040", tranferOutId = 77, }, },
		 contentScene = { { targetScene = "S057", },{ targetScene = "S058", },}, BossRefId = "monster_7045",	},
			}},
	["teamBoss_311"] = { refId = "teamBoss_311", sceneRefId = "S033", time = { duration = "19:00:00|20:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 3,
		 transfer = { transferIn = { targetScene = "S033", tranferInId = 22, }, transferOut = { targetScene = "S034", tranferOutId = 65, }, },
		 contentScene = { { targetScene = "S051", },{ targetScene = "S052", },}, BossRefId = "",	},
			}},
	["teamBoss_312"] = { refId = "teamBoss_312", sceneRefId = "S034", time = { duration = "19:00:00|20:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 3,
		 transfer = { transferIn = { targetScene = "S034", tranferInId = 24, }, transferOut = { targetScene = "S034", tranferOutId = 65, }, },
		 contentScene = { { targetScene = "S051", },{ targetScene = "S052", },}, BossRefId = "",	},
			}},
	["teamBoss_313"] = { refId = "teamBoss_313", sceneRefId = "S051", time = { duration = "19:00:00|20:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 3,
		 transfer = { transferIn = { targetScene = "S051", tranferInId = 66, }, transferOut = { targetScene = "S034", tranferOutId = 65, }, },
		 contentScene = { { targetScene = "S051", },{ targetScene = "S052", },}, BossRefId = "monster_6024",	},
			}},
	["teamBoss_314"] = { refId = "teamBoss_314", sceneRefId = "S052", time = { duration = "19:00:00|20:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 3,
		 transfer = { transferIn = { targetScene = "S052", tranferInId = 68, }, transferOut = { targetScene = "S034", tranferOutId = 65, }, },
		 contentScene = { { targetScene = "S051", },{ targetScene = "S052", },}, BossRefId = "monster_7024",	},
			}},
	["teamBoss_321"] = { refId = "teamBoss_321", sceneRefId = "S037", time = { duration = "19:00:00|20:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 3,
		 transfer = { transferIn = { targetScene = "S037", tranferInId = 30, }, transferOut = { targetScene = "S038", tranferOutId = 73, }, },
		 contentScene = { { targetScene = "S055", },{ targetScene = "S056", },}, BossRefId = "",	},
			}},
	["teamBoss_322"] = { refId = "teamBoss_322", sceneRefId = "S038", time = { duration = "19:00:00|20:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 3,
		 transfer = { transferIn = { targetScene = "S038", tranferInId = 32, }, transferOut = { targetScene = "S038", tranferOutId = 73, }, },
		 contentScene = { { targetScene = "S055", },{ targetScene = "S056", },}, BossRefId = "",	},
			}},
	["teamBoss_323"] = { refId = "teamBoss_323", sceneRefId = "S055", time = { duration = "19:00:00|20:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 3,
		 transfer = { transferIn = { targetScene = "S055", tranferInId = 74, }, transferOut = { targetScene = "S038", tranferOutId = 73, }, },
		 contentScene = { { targetScene = "S055", },{ targetScene = "S056", },}, BossRefId = "monster_6041",	},
			}},
	["teamBoss_324"] = { refId = "teamBoss_324", sceneRefId = "S056", time = { duration = "19:00:00|20:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 3,
		 transfer = { transferIn = { targetScene = "S056", tranferInId = 76, }, transferOut = { targetScene = "S038", tranferOutId = 73, }, },
		 contentScene = { { targetScene = "S055", },{ targetScene = "S056", },}, BossRefId = "monster_7041",	},
			}},
	["teamBoss_331"] = { refId = "teamBoss_331", sceneRefId = "S043", time = { duration = "19:00:00|20:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 3,
		 transfer = { transferIn = { targetScene = "S043", tranferInId = 52, }, transferOut = { targetScene = "S044", tranferOutId = 85, }, },
		 contentScene = { { targetScene = "S061", },{ targetScene = "S062", },}, BossRefId = "",	},
			}},
	["teamBoss_332"] = { refId = "teamBoss_332", sceneRefId = "S044", time = { duration = "19:00:00|20:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 3,
		 transfer = { transferIn = { targetScene = "S044", tranferInId = 54, }, transferOut = { targetScene = "S044", tranferOutId = 85, }, },
		 contentScene = { { targetScene = "S061", },{ targetScene = "S062", },}, BossRefId = "",	},
			}},
	["teamBoss_333"] = { refId = "teamBoss_333", sceneRefId = "S061", time = { duration = "19:00:00|20:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 3,
		 transfer = { transferIn = { targetScene = "S061", tranferInId = 86, }, transferOut = { targetScene = "S044", tranferOutId = 85, }, },
		 contentScene = { { targetScene = "S061", },{ targetScene = "S062", },}, BossRefId = "monster_6056",	},
			}},
	["teamBoss_334"] = { refId = "teamBoss_334", sceneRefId = "S062", time = { duration = "19:00:00|20:00:00", preStartTime = 600, preEndTime = 0,}, 
			activityData = {
				{ type = 3,
		 transfer = { transferIn = { targetScene = "S062", tranferInId = 88, }, transferOut = { targetScene = "S044", tranferOutId = 85, }, },
		 contentScene = { { targetScene = "S061", },{ targetScene = "S062", },}, BossRefId = "monster_7056",	},
			}}
}
