-- NAME: Yuanbao
-- TIME: 2014.8.6-16:23:22
-- Generated by editor

GameData = GameData or {}
GameData.Yuanbao= {
	["LYZT_YB_19800"] = { refId = "LYZT_YB_19800", level = 3, iconId = "yuanbao_3", money = 198, yuanBao = 19800, reward = 0, rewardBound = 3000, goodName = "19800元宝", firstReward = 0, firstRewardBound = 19800,},
	["LYZT_YB_3000"] = { refId = "LYZT_YB_3000", level = 5, iconId = "yuanbao_5", money = 30, yuanBao = 3000, reward = 0, rewardBound = 300, goodName = "3000元宝", firstReward = 0, firstRewardBound = 3000,},
	["LYZT_YB_32800"] = { refId = "LYZT_YB_32800", level = 2, iconId = "yuanbao_2", money = 328, yuanBao = 32800, reward = 0, rewardBound = 6400, goodName = "32800元宝", firstReward = 0, firstRewardBound = 0,},
	["LYZT_YB_600"] = { refId = "LYZT_YB_600", level = 6, iconId = "yuanbao_6", money = 6, yuanBao = 600, reward = 0, rewardBound = 0, goodName = "600元宝", firstReward = 0, firstRewardBound = 0,},
	["LYZT_YB_64800"] = { refId = "LYZT_YB_64800", level = 1, iconId = "yuanbao_1", money = 648, yuanBao = 64800, reward = 0, rewardBound = 16000, goodName = "64800元宝", firstReward = 0, firstRewardBound = 64800,},
	["LYZT_YB_9800"] = { refId = "LYZT_YB_9800", level = 4, iconId = "yuanbao_4", money = 98, yuanBao = 9800, reward = 0, rewardBound = 1200, goodName = "9800元宝", firstReward = 0, firstRewardBound = 0,}
}
