-- NAME: Medal
-- TIME: 2014.5.23-22:4:5
-- Generated by editor

GameData = GameData or {}
GameData.Medal= {
	["medal"] = { refId = "medal", name = "勋章",
			configData = {
					["equip_100_9000"] = { refId = "equip_100_9000", property = { name = "荣誉勋章 龙吟", nextMedal = "", needAchieve = 10000,}, 	},
					["equip_10_9000"] = { refId = "equip_10_9000", property = { name = "荣誉勋章 朱雀", nextMedal = "equip_20_9000", needAchieve = 1000,}, 	},
					["equip_20_9000"] = { refId = "equip_20_9000", property = { name = "荣誉勋章 玄奇", nextMedal = "equip_30_9000", needAchieve = 2000,}, 	},
					["equip_30_9000"] = { refId = "equip_30_9000", property = { name = "荣誉勋章 倚天", nextMedal = "equip_40_9000", needAchieve = 3000,}, 	},
					["equip_40_9000"] = { refId = "equip_40_9000", property = { name = "荣誉勋章 赤霄", nextMedal = "equip_50_9000", needAchieve = 4000,}, 	},
					["equip_50_9000"] = { refId = "equip_50_9000", property = { name = "荣誉勋章 天罡", nextMedal = "equip_60_9000", needAchieve = 5000,}, 	},
					["equip_60_9000"] = { refId = "equip_60_9000", property = { name = "荣誉勋章 乾坤", nextMedal = "equip_70_9000", needAchieve = 6000,}, 	},
					["equip_70_9000"] = { refId = "equip_70_9000", property = { name = "荣誉勋章 腾龙", nextMedal = "equip_80_9000", needAchieve = 7000,}, 	},
					["equip_80_9000"] = { refId = "equip_80_9000", property = { name = "荣誉勋章 太虚", nextMedal = "equip_90_9000", needAchieve = 8000,}, 	},
					["equip_90_9000"] = { refId = "equip_90_9000", property = { name = "荣誉勋章 魔神", nextMedal = "equip_100_9000", needAchieve = 9000,}, 	},
			}}
}
