-- NAME: Knight
-- TIME: 2014.6.10-21:0:3
-- Generated by editor

GameData = GameData or {}
GameData.Knight= {
	["knight_1"] = { refId = "knight_1", property = { name = "平民", iconId = "knight_1", modelId = 0, knightPreRefId = "", knightNextRefId = "knight_2", roleGrade = 30, knight = 1, minPAtk = 60, maxPAtk = 90, minPDef = 0, maxPDef = 0, minMAtk = 60, maxMAtk = 90, minMDef = 0, maxMDef = 0, minTao = 60, maxTao = 90, PImmunityPer = 0, MImmunityPer = 0, maxHP = 0, maxMP = 0, perHP = 0, perMP = 0, ignorePDef = 0, ignoreMDef = 0, moveSpeedPer = 0, atkSpeedPer = 0, crit = 0, critInjure = 0, fortune = 0, hit = 0, dodge = 0, PDodgePer = 0, MDodgePer = 0,},  knightData = {
			 upgradeSrcConsume = { { merit = 100, },}, 
			 knightSalary = { { bindedGold = 300, },}, }, },
	["knight_10"] = { refId = "knight_10", property = { name = "亲王", iconId = "knight_10", modelId = 0, knightPreRefId = "knight_9", knightNextRefId = "", roleGrade = 57, knight = 10, minPAtk = 360, maxPAtk = 540, minPDef = 0, maxPDef = 0, minMAtk = 360, maxMAtk = 540, minMDef = 0, maxMDef = 0, minTao = 360, maxTao = 540, PImmunityPer = 0, MImmunityPer = 0, maxHP = 0, maxMP = 0, perHP = 0, perMP = 0, ignorePDef = 0, ignoreMDef = 0, moveSpeedPer = 0, atkSpeedPer = 0, crit = 0, critInjure = 0, fortune = 0, hit = 0, dodge = 0, PDodgePer = 0, MDodgePer = 0,},  knightData = {
			 upgradeSrcConsume = "", 
			 knightSalary = { { bindedGold = 1200, },}, }, },
	["knight_2"] = { refId = "knight_2", property = { name = "骑士", iconId = "knight_2", modelId = 0, knightPreRefId = "knight_1", knightNextRefId = "knight_3", roleGrade = 33, knight = 2, minPAtk = 100, maxPAtk = 150, minPDef = 0, maxPDef = 0, minMAtk = 100, maxMAtk = 150, minMDef = 0, maxMDef = 0, minTao = 100, maxTao = 150, PImmunityPer = 0, MImmunityPer = 0, maxHP = 0, maxMP = 0, perHP = 0, perMP = 0, ignorePDef = 0, ignoreMDef = 0, moveSpeedPer = 0, atkSpeedPer = 0, crit = 0, critInjure = 0, fortune = 0, hit = 0, dodge = 0, PDodgePer = 0, MDodgePer = 0,},  knightData = {
			 upgradeSrcConsume = { { merit = 300, },}, 
			 knightSalary = { { bindedGold = 400, },}, }, },
	["knight_3"] = { refId = "knight_3", property = { name = "爵士", iconId = "knight_3", modelId = 0, knightPreRefId = "knight_2", knightNextRefId = "knight_4", roleGrade = 36, knight = 3, minPAtk = 120, maxPAtk = 180, minPDef = 0, maxPDef = 0, minMAtk = 120, maxMAtk = 180, minMDef = 0, maxMDef = 0, minTao = 120, maxTao = 180, PImmunityPer = 0, MImmunityPer = 0, maxHP = 0, maxMP = 0, perHP = 0, perMP = 0, ignorePDef = 0, ignoreMDef = 0, moveSpeedPer = 0, atkSpeedPer = 0, crit = 0, critInjure = 0, fortune = 0, hit = 0, dodge = 0, PDodgePer = 0, MDodgePer = 0,},  knightData = {
			 upgradeSrcConsume = { { merit = 600, },}, 
			 knightSalary = { { bindedGold = 500, },}, }, },
	["knight_4"] = { refId = "knight_4", property = { name = "勋爵", iconId = "knight_4", modelId = 0, knightPreRefId = "knight_3", knightNextRefId = "knight_5", roleGrade = 39, knight = 4, minPAtk = 160, maxPAtk = 240, minPDef = 0, maxPDef = 0, minMAtk = 160, maxMAtk = 240, minMDef = 0, maxMDef = 0, minTao = 160, maxTao = 240, PImmunityPer = 0, MImmunityPer = 0, maxHP = 0, maxMP = 0, perHP = 0, perMP = 0, ignorePDef = 0, ignoreMDef = 0, moveSpeedPer = 0, atkSpeedPer = 0, crit = 0, critInjure = 0, fortune = 0, hit = 0, dodge = 0, PDodgePer = 0, MDodgePer = 0,},  knightData = {
			 upgradeSrcConsume = { { merit = 1000, },}, 
			 knightSalary = { { bindedGold = 600, },}, }, },
	["knight_5"] = { refId = "knight_5", property = { name = "男爵", iconId = "knight_5", modelId = 0, knightPreRefId = "knight_4", knightNextRefId = "knight_6", roleGrade = 42, knight = 5, minPAtk = 180, maxPAtk = 270, minPDef = 0, maxPDef = 0, minMAtk = 180, maxMAtk = 270, minMDef = 0, maxMDef = 0, minTao = 180, maxTao = 270, PImmunityPer = 0, MImmunityPer = 0, maxHP = 0, maxMP = 0, perHP = 0, perMP = 0, ignorePDef = 0, ignoreMDef = 0, moveSpeedPer = 0, atkSpeedPer = 0, crit = 0, critInjure = 0, fortune = 0, hit = 0, dodge = 0, PDodgePer = 0, MDodgePer = 0,},  knightData = {
			 upgradeSrcConsume = { { merit = 1800, },}, 
			 knightSalary = { { bindedGold = 700, },}, }, },
	["knight_6"] = { refId = "knight_6", property = { name = "子爵", iconId = "knight_6", modelId = 0, knightPreRefId = "knight_5", knightNextRefId = "knight_7", roleGrade = 45, knight = 6, minPAtk = 220, maxPAtk = 330, minPDef = 0, maxPDef = 0, minMAtk = 220, maxMAtk = 330, minMDef = 0, maxMDef = 0, minTao = 220, maxTao = 330, PImmunityPer = 0, MImmunityPer = 0, maxHP = 0, maxMP = 0, perHP = 0, perMP = 0, ignorePDef = 0, ignoreMDef = 0, moveSpeedPer = 0, atkSpeedPer = 0, crit = 0, critInjure = 0, fortune = 0, hit = 0, dodge = 0, PDodgePer = 0, MDodgePer = 0,},  knightData = {
			 upgradeSrcConsume = { { merit = 3500, },}, 
			 knightSalary = { { bindedGold = 800, },}, }, },
	["knight_7"] = { refId = "knight_7", property = { name = "伯爵", iconId = "knight_7", modelId = 0, knightPreRefId = "knight_6", knightNextRefId = "knight_8", roleGrade = 48, knight = 7, minPAtk = 260, maxPAtk = 390, minPDef = 0, maxPDef = 0, minMAtk = 260, maxMAtk = 390, minMDef = 0, maxMDef = 0, minTao = 260, maxTao = 390, PImmunityPer = 0, MImmunityPer = 0, maxHP = 0, maxMP = 0, perHP = 0, perMP = 0, ignorePDef = 0, ignoreMDef = 0, moveSpeedPer = 0, atkSpeedPer = 0, crit = 0, critInjure = 0, fortune = 0, hit = 0, dodge = 0, PDodgePer = 0, MDodgePer = 0,},  knightData = {
			 upgradeSrcConsume = { { merit = 6400, },}, 
			 knightSalary = { { bindedGold = 900, },}, }, },
	["knight_8"] = { refId = "knight_8", property = { name = "侯爵", iconId = "knight_8", modelId = 0, knightPreRefId = "knight_7", knightNextRefId = "knight_9", roleGrade = 51, knight = 8, minPAtk = 300, maxPAtk = 450, minPDef = 0, maxPDef = 0, minMAtk = 300, maxMAtk = 450, minMDef = 0, maxMDef = 0, minTao = 300, maxTao = 450, PImmunityPer = 0, MImmunityPer = 0, maxHP = 0, maxMP = 0, perHP = 0, perMP = 0, ignorePDef = 0, ignoreMDef = 0, moveSpeedPer = 0, atkSpeedPer = 0, crit = 0, critInjure = 0, fortune = 0, hit = 0, dodge = 0, PDodgePer = 0, MDodgePer = 0,},  knightData = {
			 upgradeSrcConsume = { { merit = 12000, },}, 
			 knightSalary = { { bindedGold = 1000, },}, }, },
	["knight_9"] = { refId = "knight_9", property = { name = "公爵", iconId = "knight_9", modelId = 0, knightPreRefId = "knight_8", knightNextRefId = "knight_10", roleGrade = 54, knight = 9, minPAtk = 320, maxPAtk = 480, minPDef = 0, maxPDef = 0, minMAtk = 320, maxMAtk = 480, minMDef = 0, maxMDef = 0, minTao = 320, maxTao = 480, PImmunityPer = 0, MImmunityPer = 0, maxHP = 0, maxMP = 0, perHP = 0, perMP = 0, ignorePDef = 0, ignoreMDef = 0, moveSpeedPer = 0, atkSpeedPer = 0, crit = 0, critInjure = 0, fortune = 0, hit = 0, dodge = 0, PDodgePer = 0, MDodgePer = 0,},  knightData = {
			 upgradeSrcConsume = { { merit = 30000, },}, 
			 knightSalary = { { bindedGold = 1100, },}, }, }
}
