-- NAME: EquipBest
-- TIME: 2014.5.26-18:29:29
-- Generated by editor

GameData = GameData or {}
GameData.EquipBest= {
	["level_30_1_0"] = { refId = "level_30_1_0", level = 40, profession = 1, gender = 0, equitId = "equip_40_1101",},
	["level_30_2_0"] = { refId = "level_30_2_0", level = 40, profession = 2, gender = 0, equitId = "equip_40_1202",},
	["level_30_3_0"] = { refId = "level_30_3_0", level = 40, profession = 3, gender = 0, equitId = "equip_40_1301",},
	["level_40_1_0"] = { refId = "level_40_1_0", level = 50, profession = 1, gender = 0, equitId = "equip_50_1104",},
	["level_40_2_0"] = { refId = "level_40_2_0", level = 50, profession = 2, gender = 0, equitId = "equip_50_1201",},
	["level_40_3_0"] = { refId = "level_40_3_0", level = 50, profession = 3, gender = 0, equitId = "equip_50_1305",},
	["level_50_1_0"] = { refId = "level_50_1_0", level = 60, profession = 1, gender = 0, equitId = "equip_60_1103",},
	["level_50_2_0"] = { refId = "level_50_2_0", level = 60, profession = 2, gender = 0, equitId = "equip_60_1204",},
	["level_50_3_0"] = { refId = "level_50_3_0", level = 60, profession = 3, gender = 0, equitId = "equip_60_1303",},
	["level_60_1_0"] = { refId = "level_60_1_0", level = 70, profession = 1, gender = 0, equitId = "equip_70_1102",},
	["level_60_2_0"] = { refId = "level_60_2_0", level = 70, profession = 2, gender = 0, equitId = "equip_70_1203",},
	["level_60_3_0"] = { refId = "level_60_3_0", level = 70, profession = 3, gender = 0, equitId = "equip_70_1302",}
}
