-- NAME: PropsPurchase
-- TIME: 2014.6.18-20:23:56
-- Generated by editor

GameData = GameData or {}
GameData.PropsPurchase= {
	["item_drug_1"] = { refId = "item_drug_1", name = "疗伤药(小)", defaultNumber = 99,},
	["item_drug_2"] = { refId = "item_drug_2", name = "疗伤药(中)", defaultNumber = 99,},
	["item_drug_3"] = { refId = "item_drug_3", name = "疗伤药(大)", defaultNumber = 99,},
	["item_drug_4"] = { refId = "item_drug_4", name = "魔法药(小)", defaultNumber = 99,},
	["item_drug_5"] = { refId = "item_drug_5", name = "魔法药(中)", defaultNumber = 99,},
	["item_drug_6"] = { refId = "item_drug_6", name = "魔法药(大)", defaultNumber = 99,},
	["item_drug_7"] = { refId = "item_drug_7", name = "太阳水(小)", defaultNumber = 6,},
	["item_drug_8"] = { refId = "item_drug_8", name = "太阳水(大)", defaultNumber = 6,},
	["item_drug_9"] = { refId = "item_drug_9", name = "超级太阳水", defaultNumber = 6,}
}
