-- NAME: UnPropsItem
-- TIME: 2014.3.11-20:14:57
-- Generated by editor

GameData = GameData or {}
GameData.UnPropsItem= {
	["achievement"] = { refId = "achievement", property = { name = "成就点", description = "可兑换勋章", iconId = "item_achievement",}, },
	["bindedGold"] = { refId = "bindedGold", property = { name = "绑定元宝", description = "绑定元宝", iconId = "item_bindedGold",}, },
	["exp"] = { refId = "exp", property = { name = "经验", description = "经验", iconId = "item_exp",}, },
	["gold"] = { refId = "gold", property = { name = "金币", description = "金币", iconId = "item_gold",}, },
	["merit"] = { refId = "merit", property = { name = "功勋", description = "可升级爵位", iconId = "item_merit",}, },
	["unbindedGold"] = { refId = "unbindedGold", property = { name = "元宝", description = "元宝", iconId = "item_unbindedGold",}, }
}
