-- NAME: UnionGameInstance
-- TIME: 2014.7.10-12:22:46
-- Generated by editor

GameData = GameData or {}
GameData.UnionGameInstance= {
	["unionGameInstance"] = { refId = "unionGameInstance", property = { maxStackNumber = 10, gold = 1000000, monsterRefId = "monster_8002", sceneRefId = "S013", itemRefId = "item_gift_4", bindStatus = 1, openTime = "15:00:00|16:00:00",}, }
}
