-- NAME: AllIns_PK
-- TIME: 2014.6.4-15:0:32
-- Generated by editor

GameData = GameData or {}
GameData.AllIns_PK= {
	["Ins_pk1"] = { refId = "Ins_pk1",},
	["Ins_pk2"] = { refId = "Ins_pk2",},
	["Ins_pk3"] = { refId = "Ins_pk3",},
	["Ins_pk4"] = { refId = "Ins_pk4",},
	["Ins_pk5"] = { refId = "Ins_pk5",}
}
