-- NAME: Ins_5
-- TIME: 2014.6.16-19:1:32
-- Generated by editor

GameData = GameData or {}
GameData.Ins_5= {
	["Ins_5"] = { refId = "Ins_5", instanceType = 1, name = "勇闯魔窟", introduce = "65级副本，恶魔必死，奖励丰厚更有护身戒指碎片", suggestlevel = 65,
			configData = {
					["game_instance"] = { refId = "game_instance", name = "Ins_5 任务总表",
			configData = {
					["Ins_5"] = { refId = "Ins_5", gameInstanceData = { openDetailsData = "00:00:00|86400",
			 structureDetails = { "I105", }, },  property = { questRefId = "", timesADay = 2, timesAWeek = 0, level = 40, isTeam = 0, name = "黑影秘窟",},  name = "黑影秘窟", description = "击败全部怪物可完成副本，点击挂机按钮事半功倍，点击出口按钮即可离开副本。",	},
			}	},
					["game_instance_quest"] = { refId = "game_instance_quest", name = "副本任务表",
			configData = {
					["quest_1"] = { refId = "quest_1", name = "巨人的逆袭", description = "击败12个{mouster_8050}。", property = { questType = 1, rewardImmediately = 0,},  questData = {
			 orderField = { { killCount = 12, monsterRefId = "monster_8050", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 100000, }, }, }, 	},
					["quest_2"] = { refId = "quest_2", name = "沙虫围城", description = "击败16只{monster_8013}。", property = { questType = 1, rewardImmediately = 0,},  questData = {
			 orderField = { { killCount = 16, monsterRefId = "monster_8013", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 150000, }, }, }, 	},
					["quest_3"] = { refId = "quest_3", name = "多角虫卫队", description = "击败2个{monster_8014}。", property = { questType = 1, rewardImmediately = 0,},  questData = {
			 orderField = { { killCount = 2, monsterRefId = "monster_8014", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 50000, }, }, }, 	},
					["quest_4"] = { refId = "quest_4", name = "5分钟内击败恶魔", description = "在5分钟内击败{monster_8053}。", property = { questType = 9, rewardImmediately = 0,},  questData = {
			 orderField = { { killCount = 1, monsterRefId = "monster_8053", orderType = 9, timeCount = 300, },}, 
			 rewardField = { propertyReward = { exp = 900000, }, }, }, 	},
			}	},
					["game_instance_scene"] = { refId = "game_instance_scene", name = "副本层总表",
			configData = {
					["I105"] = { refId = "I105", property = { sceneRefId = "S105", succeedType = 1,},  mapId = 105, description = "击败全部怪物", gameInstanceSceneData = { succeedConditionData = "monster_8053=1&monster_8014=2&monster_8050=12&monster_8013=16",
			 consumptionItems = "", 
			 conditionField = { "quest_1", "quest_2", "quest_3", "quest_4", }, }, 	},
			}	},
			}}
}
