-- NAME: Ins_7
-- TIME: 2014.6.16-19:1:33
-- Generated by editor

GameData = GameData or {}
GameData.Ins_7= {
	["Ins_7"] = { refId = "Ins_7", instanceType = 1, name = "战神庭院", introduce = "70级副本，探索险境，奖励丰厚更有重生戒指碎片", suggestlevel = 70,
			configData = {
					["game_instance"] = { refId = "game_instance", name = "Ins_7 任务总表",
			configData = {
					["Ins_7"] = { refId = "Ins_7", gameInstanceData = { openDetailsData = "00:00:00|86400",
			 structureDetails = { "I107", }, },  property = { questRefId = "", timesADay = 2, timesAWeek = 0, level = 40, isTeam = 0, name = "黑影秘窟",},  name = "黑影秘窟", description = "击败全部怪物可完成副本，点击挂机按钮事半功倍，点击出口按钮即可离开副本。",	},
			}	},
					["game_instance_quest"] = { refId = "game_instance_quest", name = "副本任务表",
			configData = {
					["quest_1"] = { refId = "quest_1", name = "猪卫的逆袭", description = "击败16个{mouster_8054}。", property = { questType = 1, rewardImmediately = 0,},  questData = {
			 orderField = { { killCount = 16, monsterRefId = "monster_8054", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 200000, }, }, }, 	},
					["quest_2"] = { refId = "quest_2", name = "蝎的真身", description = "击败5只{monster_8055}。", property = { questType = 1, rewardImmediately = 0,},  questData = {
			 orderField = { { killCount = 5, monsterRefId = "monster_8055", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 100000, }, }, }, 	},
					["quest_3"] = { refId = "quest_3", name = "虹魔之死", description = "击败1个{monster_8056}。", property = { questType = 1, rewardImmediately = 0,},  questData = {
			 orderField = { { killCount = 1, monsterRefId = "monster_8056", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 1200000, }, }, }, 	},
			}	},
					["game_instance_scene"] = { refId = "game_instance_scene", name = "副本层总表",
			configData = {
					["I107"] = { refId = "I107", property = { sceneRefId = "S107", succeedType = 1,},  mapId = 107, description = "击败全部怪物", gameInstanceSceneData = { succeedConditionData = "monster_8054=16&monster_8055=5&monster_8056=1",
			 consumptionItems = "", 
			 conditionField = { "quest_1", "quest_2", "quest_3", }, }, 	},
			}	},
			}}
}
