-- NAME: Ins_pk2
-- TIME: 2014.6.16-19:1:35
-- Generated by editor

GameData = GameData or {}
GameData.Ins_pk2= {
	["Ins_pk2"] = { refId = "Ins_pk2", instanceType = 3, name = "重返尸王殿", introduce = "",
			configData = {
					["game_instance"] = { refId = "game_instance", name = "Ins_pk2 任务总表",
			configData = {
					["Ins_pk2"] = { refId = "Ins_pk2", gameInstanceData = { openDetailsData = "00:00:00|86400",
			 structureDetails = { "I101", }, },  property = { questRefId = "", timesADay = 10, timesAWeek = 0, level = 1, isTeam = 0, name = "惩治仇敌",},  name = "惩治仇敌", description = "击败全部仇人",	},
			}	},
					["game_instance_quest"] = { refId = "game_instance_quest", name = "副本任务表",
			configData = {
					["quest_1"] = { refId = "quest_1", name = "击败战士", description = "击败{monster_1004}。", property = { questType = 1, rewardImmediately = 0,},  questData = {
			 orderField = { { killCount = 1, monsterRefId = "monster_1004", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 10000, gold = 10000, }, }, }, 	},
					["quest_2"] = { refId = "quest_2", name = "击败法师", description = "击败{monster_1005}。", property = { questType = 1, rewardImmediately = 0,},  questData = {
			 orderField = { { killCount = 1, monsterRefId = "monster_1005", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 10000, gold = 10000, }, }, }, 	},
					["quest_3"] = { refId = "quest_3", name = "击败道士", description = "击败{monster_1006}。", property = { questType = 1, rewardImmediately = 0,},  questData = {
			 orderField = { { killCount = 1, monsterRefId = "monster_1006", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 10000, gold = 10000, }, }, }, 	},
			}	},
					["game_instance_scene"] = { refId = "game_instance_scene", name = "副本层总表",
			configData = {
					["I152"] = { refId = "I152", property = { sceneRefId = "S152", succeedType = 1,},  mapId = 152, description = "击败所有敌人", gameInstanceSceneData = { succeedConditionData = "monster_1004=1&monster_1005=1&monster_1006=1",
			 consumptionItems = "", 
			 conditionField = { "quest_1", "quest_2", "quest_3", }, }, 	},
			}	},
			}}
}
