-- NAME: Ins_2
-- TIME: 2014.6.16-19:1:30
-- Generated by editor

GameData = GameData or {}
GameData.Ins_2= {
	["Ins_2"] = { refId = "Ins_2", instanceType = 1, name = "秘密营地", introduce = "50级副本，驱逐魔族，奖励丰厚更有传世奇书碎片", suggestlevel = 50,
			configData = {
					["game_instance"] = { refId = "game_instance", name = "Ins_2 任务总表",
			configData = {
					["Ins_2"] = { refId = "Ins_2", gameInstanceData = { openDetailsData = "00:00:00|86400",
			 structureDetails = { "I102", }, },  property = { questRefId = "", timesADay = 2, timesAWeek = 0, level = 40, isTeam = 0, name = "猪洞巢穴",},  name = "猪洞巢穴", description = "击败全部怪物可完成副本，点击挂机按钮事半功倍，点击出口按钮即可离开副本。",	},
			}	},
					["game_instance_quest"] = { refId = "game_instance_quest", name = "副本任务表",
			configData = {
					["quest_1"] = { refId = "quest_1", name = "消灭狼群", description = "击败17个{monster_8011}。", property = { questType = 1, rewardImmediately = 0,},  questData = {
			 orderField = { { killCount = 17, monsterRefId = "monster_8011", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 100000, }, }, }, 	},
					["quest_2"] = { refId = "quest_2", name = "邪恶退散", description = "击败{monster_8042}。", property = { questType = 1, rewardImmediately = 0,},  questData = {
			 orderField = { { killCount = 1, monsterRefId = "monster_8042", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 50000, }, }, }, 	},
					["quest_3"] = { refId = "quest_3", name = "人蛇大战", description = "击败{monster_8012}。", property = { questType = 1, rewardImmediately = 0,},  questData = {
			 orderField = { { killCount = 1, monsterRefId = "monster_8012", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 50000, }, }, }, 	},
					["quest_4"] = { refId = "quest_4", name = "猪王之王", description = "击败{monster_8045}。", property = { questType = 1, rewardImmediately = 0,},  questData = {
			 orderField = { { killCount = 1, monsterRefId = "monster_8045", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 300000, }, }, }, 	},
			}	},
					["game_instance_scene"] = { refId = "game_instance_scene", name = "副本层总表",
			configData = {
					["I102"] = { refId = "I102", property = { sceneRefId = "S102", succeedType = 1,},  mapId = 102, description = "击败全部怪物", gameInstanceSceneData = { succeedConditionData = "monster_8011=17&monster_8042=1&monster_8012=1&monster_8045=1",
			 consumptionItems = "", 
			 conditionField = { "quest_1", "quest_2", "quest_3", "quest_4", }, }, 	},
			}	},
			}}
}
