-- NAME: Ins_8
-- TIME: 2014.7.15-16:0:49
-- Generated by editor

GameData = GameData or {}
GameData.Ins_8= {
	["Ins_8"] = { refId = "Ins_8", instanceType = 4, name = "公会副本", introduce = "公会副本，捕获教主，奖励丰厚更有点金手碎片", suggestlevel = 45,
			configData = {
					["game_instance"] = { refId = "game_instance", name = "Ins_1 任务总表",
			configData = {
					["Ins_8"] = { refId = "Ins_8", gameInstanceData = { openDetailsData = "15:00:00|3600",
			 structureDetails = { "I013", }, },  property = { questRefId = "", timesADay = 0, timesAWeek = 0, level = 1, isTeam = 1, name = "公会副本",},  name = "公会副本", description = "击败全部怪物可完成副本，点击挂机按钮事半功倍，点击出口按钮即可离开副本。",	},
			}	},
					["game_instance_quest"] = { refId = "game_instance_quest", name = "副本任务表",
			configData = {
					["quest_1"] = { refId = "quest_1", name = "暴怒麒麟", description = "击败{mouster_8002}。", property = { questType = 1, rewardImmediately = 0,},  questData = {
			 orderField = { { killCount = 1, monsterRefId = "monster_8002", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 200000, }, }, }, 	},
			}	},
					["game_instance_scene"] = { refId = "game_instance_scene", name = "副本层总表",
			configData = {
					["I013"] = { refId = "I013", property = { sceneRefId = "S013", succeedType = 1,},  mapId = 13, description = "击败全部怪物", gameInstanceSceneData = { succeedConditionData = "monster_8002=1",
			 consumptionItems = "", 
			 conditionField = { "quest_1", }, }, 	},
			}	},
			}}
}
