-- NAME: Ins_6
-- TIME: 2014.7.9-11:36:49
-- Generated by editor

GameData = GameData or {}
GameData.Ins_6= {
	["Ins_6"] = { refId = "Ins_6", instanceType = 2, name = "勇闯镇魔塔", introduce = "勇闯魔塔,千万经验,还有装备拿！",
			configData = {
					["game_instance"] = { refId = "game_instance", name = "Ins_6 任务总表",
			configData = {
					["Ins_6"] = { refId = "Ins_6", gameInstanceData = { openDetailsData = "00:00:00|86400",
			 structureDetails = { "S201", "S202", "S203", "S204", "S205", "S206", "S207", "S208", "S209", "S210", "S211", "S212", "S213", "S214", "S215", }, },  property = { questRefId = "", timesADay = 1, timesAWeek = 0, level = 43, isTeam = 0, name = "勇闯镇魔塔",},  name = "勇闯镇魔塔", description = "前往镇魔塔，获取海量经验值，击败boss还可拿装备！",	},
			}	},
					["game_instance_quest"] = { refId = "game_instance_quest", name = "副本任务表",
			configData = {
					["quest_1"] = { refId = "quest_1", name = "驱逐镇魔骷髅", description = "击败2个{monster_2000}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 2, monsterRefId = "monster_2000", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 50000, }, }, }, 	},
					["quest_10"] = { refId = "quest_10", name = "驱逐镇魔掷斧骷髅", description = "击败2个{monster_2001}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 2, monsterRefId = "monster_2001", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 80000, }, }, }, 	},
					["quest_11"] = { refId = "quest_11", name = "驱逐镇魔骷髅战将", description = "击败6个{monster_2002}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 6, monsterRefId = "monster_2002", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 330000, }, }, }, 	},
					["quest_12"] = { refId = "quest_12", name = "驱逐镇魔骷髅", description = "击败9个{monster_2000}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 9, monsterRefId = "monster_2000", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 250000, }, }, }, 	},
					["quest_13"] = { refId = "quest_13", name = "教主冰替身之死", description = "击败{monster_2004}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 1, monsterRefId = "monster_2004", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 290000, }, }, }, 	},
					["quest_14"] = { refId = "quest_14", name = "驱逐镇魔骷髅", description = "击败8个{monster_2000}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 8, monsterRefId = "monster_2000", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 250000, }, }, }, 	},
					["quest_15"] = { refId = "quest_15", name = "驱逐镇魔掷斧骷髅", description = "击败7个{monster_2001}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 7, monsterRefId = "monster_2001", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 310000, }, }, }, 	},
					["quest_16"] = { refId = "quest_16", name = "驱逐镇魔掷斧骷髅", description = "击败12个{monster_2001}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 12, monsterRefId = "monster_2001", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 420000, }, }, }, 	},
					["quest_17"] = { refId = "quest_17", name = "驱逐镇魔骷髅战将", description = "击败3个{monster_2002}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 3, monsterRefId = "monster_2002", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 210000, }, }, }, 	},
					["quest_18"] = { refId = "quest_18", name = "驱逐镇魔骷髅", description = "击败8个{monster_2000}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 8, monsterRefId = "monster_2000", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 210000, }, }, }, 	},
					["quest_19"] = { refId = "quest_19", name = "驱逐镇魔掷斧骷髅", description = "击败6个{monster_2001}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 6, monsterRefId = "monster_2001", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 230000, }, }, }, 	},
					["quest_2"] = { refId = "quest_2", name = "驱逐镇魔掷斧骷髅", description = "击败{monster_2001}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 1, monsterRefId = "monster_2001", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 40000, }, }, }, 	},
					["quest_20"] = { refId = "quest_20", name = "教主火替身之死", description = "击败{monster_2005}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 1, monsterRefId = "monster_2005", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 310000, }, }, }, 	},
					["quest_21"] = { refId = "quest_21", name = "驱逐镇魔骷髅", description = "击败10个{monster_2000}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 10, monsterRefId = "monster_2000", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 330000, }, }, }, 	},
					["quest_22"] = { refId = "quest_22", name = "驱逐镇魔掷斧骷髅", description = "击败5个{monster_2001}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 5, monsterRefId = "monster_2001", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 210000, }, }, }, 	},
					["quest_23"] = { refId = "quest_23", name = "驱逐镇魔骷髅战将", description = "击败5个{monster_2002}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 5, monsterRefId = "monster_2002", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 250000, }, }, }, 	},
					["quest_24"] = { refId = "quest_24", name = "驱逐镇魔骷髅", description = "击败5个{monster_2000}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 5, monsterRefId = "monster_2000", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 170000, }, }, }, 	},
					["quest_25"] = { refId = "quest_25", name = "驱逐镇魔掷斧骷髅", description = "击败10个{monster_2001}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 10, monsterRefId = "monster_2001", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 420000, }, }, }, 	},
					["quest_26"] = { refId = "quest_26", name = "驱逐镇魔骷髅战将", description = "击败5个{monster_2002}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 5, monsterRefId = "monster_2002", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 250000, }, }, }, 	},
					["quest_27"] = { refId = "quest_27", name = "驱逐镇魔骷髅", description = "击败15个{monster_2000}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 15, monsterRefId = "monster_2000", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 420000, }, }, }, 	},
					["quest_28"] = { refId = "quest_28", name = "驱逐镇魔掷斧骷髅", description = "击败4个{monster_2001}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 4, monsterRefId = "monster_2001", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 170000, }, }, }, 	},
					["quest_29"] = { refId = "quest_29", name = "教主毒替身之死", description = "击败{monster_2006}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 1, monsterRefId = "monster_2006", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 380000, }, }, }, 	},
					["quest_3"] = { refId = "quest_3", name = "驱逐镇魔骷髅", description = "击败8个{monster_2000}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 8, monsterRefId = "monster_2000", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 270000, }, }, }, 	},
					["quest_30"] = { refId = "quest_30", name = "驱逐镇魔骷髅", description = "击败10个{monster_2000}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 10, monsterRefId = "monster_2000", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 310000, }, }, }, 	},
					["quest_31"] = { refId = "quest_31", name = "驱逐镇魔掷斧骷髅", description = "击败10个{monster_2001}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 10, monsterRefId = "monster_2001", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 420000, }, }, }, 	},
					["quest_32"] = { refId = "quest_32", name = "驱逐镇魔骷髅战将", description = "击败5个{monster_2002}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 5, monsterRefId = "monster_2002", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 250000, }, }, }, 	},
					["quest_33"] = { refId = "quest_33", name = "驱逐镇魔骷髅", description = "击败10个{monster_2000}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 10, monsterRefId = "monster_2000", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 310000, }, }, }, 	},
					["quest_34"] = { refId = "quest_34", name = "驱逐镇魔掷斧骷髅", description = "击败5个{monster_2001}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 5, monsterRefId = "monster_2001", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 210000, }, }, }, 	},
					["quest_35"] = { refId = "quest_35", name = "驱逐镇魔骷髅战将", description = "击败10个{monster_2002}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 10, monsterRefId = "monster_2002", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 500000, }, }, }, 	},
					["quest_36"] = { refId = "quest_36", name = "驱逐镇魔骷髅", description = "击败15个{monster_2000}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 15, monsterRefId = "monster_2000", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 460000, }, }, }, 	},
					["quest_37"] = { refId = "quest_37", name = "驱逐镇魔掷斧骷髅", description = "击败8个{monster_2001}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 8, monsterRefId = "monster_2001", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 330000, }, }, }, 	},
					["quest_38"] = { refId = "quest_38", name = "击败祖玛教主真身", description = "击败{monster_2007}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 1, monsterRefId = "monster_2007", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 420000, }, }, }, 	},
					["quest_4"] = { refId = "quest_4", name = "驱逐镇魔骷髅战将", description = "击败{monster_2002}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 1, monsterRefId = "monster_2002", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 50000, }, }, }, 	},
					["quest_5"] = { refId = "quest_5", name = "驱逐镇魔骷髅", description = "击败5个{monster_2000}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 5, monsterRefId = "monster_2000", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 150000, }, }, }, 	},
					["quest_6"] = { refId = "quest_6", name = "教主雷替身之死", description = "击败{monster_2003}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 1, monsterRefId = "monster_2003", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 230000, }, }, }, 	},
					["quest_7"] = { refId = "quest_7", name = "驱逐镇魔掷斧骷髅", description = "击败8个{monster_2001}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 8, monsterRefId = "monster_2001", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 350000, }, }, }, 	},
					["quest_8"] = { refId = "quest_8", name = "驱逐镇魔骷髅战将", description = "击败2个{monster_2002}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 2, monsterRefId = "monster_2002", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 100000, }, }, }, 	},
					["quest_9"] = { refId = "quest_9", name = "驱逐镇魔骷髅", description = "击败2个{monster_2000}。", property = { questType = 1, rewardImmediately = 1,},  questData = {
			 orderField = { { killCount = 2, monsterRefId = "monster_2000", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 60000, }, }, }, 	},
			}	},
					["game_instance_scene"] = { refId = "game_instance_scene", name = "副本层总表",
			configData = {
					["S201"] = { refId = "S201", property = { sceneRefId = "S201", succeedType = 1,},  mapId = 201, description = "击败本层全部怪物", gameInstanceSceneData = { succeedConditionData = "monster_2000=2&monster_2001=1",
			 consumptionItems = { item = { itemCount = 6, itemRefId = "item_zhenmoling_1", }, }, 
			 conditionField = { "quest_1", "quest_2", }, }, 	},
					["S202"] = { refId = "S202", property = { sceneRefId = "S202", succeedType = 1,},  mapId = 202, description = "击败本层全部怪物", gameInstanceSceneData = { succeedConditionData = "monster_2000=8&monster_2002=1",
			 consumptionItems = { item = { itemCount = 7, itemRefId = "item_zhenmoling_1", }, }, 
			 conditionField = { "quest_3", "quest_4", }, }, 	},
					["S203"] = { refId = "S203", property = { sceneRefId = "S203", succeedType = 1,},  mapId = 203, description = "击败本层全部怪物", gameInstanceSceneData = { succeedConditionData = "monster_2000=5&monster_2003=1",
			 consumptionItems = { item = { itemCount = 9, itemRefId = "item_zhenmoling_1", }, }, 
			 conditionField = { "quest_5", "quest_6", }, }, 	},
					["S204"] = { refId = "S204", property = { sceneRefId = "S204", succeedType = 1,},  mapId = 204, description = "击败本层全部怪物", gameInstanceSceneData = { succeedConditionData = "monster_2001=8&monster_2002=2",
			 consumptionItems = { item = { itemCount = 10, itemRefId = "item_zhenmoling_1", }, }, 
			 conditionField = { "quest_7", "quest_8", }, }, 	},
					["S205"] = { refId = "S205", property = { sceneRefId = "S205", succeedType = 1,},  mapId = 205, description = "击败本层全部怪物", gameInstanceSceneData = { succeedConditionData = "monster_2000=2&monster_2001=2&monster_2002=6",
			 consumptionItems = { item = { itemCount = 15, itemRefId = "item_zhenmoling_1", }, }, 
			 conditionField = { "quest_9", "quest_10", "quest_11", }, }, 	},
					["S206"] = { refId = "S206", property = { sceneRefId = "S206", succeedType = 1,},  mapId = 206, description = "击败本层全部怪物", gameInstanceSceneData = { succeedConditionData = "monster_2000=9&monster_2004=1",
			 consumptionItems = { item = { itemCount = 17, itemRefId = "item_zhenmoling_1", }, }, 
			 conditionField = { "quest_12", "quest_13", }, }, 	},
					["S207"] = { refId = "S207", property = { sceneRefId = "S207", succeedType = 1,},  mapId = 207, description = "击败本层全部怪物", gameInstanceSceneData = { succeedConditionData = "monster_2000=8&monster_2001=7",
			 consumptionItems = { item = { itemCount = 20, itemRefId = "item_zhenmoling_1", }, }, 
			 conditionField = { "quest_14", "quest_15", }, }, 	},
					["S208"] = { refId = "S208", property = { sceneRefId = "S208", succeedType = 1,},  mapId = 208, description = "击败本层全部怪物", gameInstanceSceneData = { succeedConditionData = "monster_2001=12&monster_2002=3",
			 consumptionItems = { item = { itemCount = 25, itemRefId = "item_zhenmoling_1", }, }, 
			 conditionField = { "quest_16", "quest_17", }, }, 	},
					["S209"] = { refId = "S209", property = { sceneRefId = "S209", succeedType = 1,},  mapId = 209, description = "击败本层全部怪物", gameInstanceSceneData = { succeedConditionData = "monster_2000=8&monster_2001=6&monster_2005=1",
			 consumptionItems = { item = { itemCount = 27, itemRefId = "item_zhenmoling_1", }, }, 
			 conditionField = { "quest_18", "quest_19", "quest_20", }, }, 	},
					["S210"] = { refId = "S210", property = { sceneRefId = "S210", succeedType = 1,},  mapId = 210, description = "击败本层全部怪物", gameInstanceSceneData = { succeedConditionData = "monster_2000=10&monster_2001=5&monster_2002=5",
			 consumptionItems = { item = { itemCount = 30, itemRefId = "item_zhenmoling_1", }, }, 
			 conditionField = { "quest_21", "quest_22", "quest_23", }, }, 	},
					["S211"] = { refId = "S211", property = { sceneRefId = "S211", succeedType = 1,},  mapId = 211, description = "击败本层全部怪物", gameInstanceSceneData = { succeedConditionData = "monster_2000=5&monster_2001=10&monster_2002=5",
			 consumptionItems = { item = { itemCount = 35, itemRefId = "item_zhenmoling_1", }, }, 
			 conditionField = { "quest_24", "quest_25", "quest_26", }, }, 	},
					["S212"] = { refId = "S212", property = { sceneRefId = "S212", succeedType = 1,},  mapId = 212, description = "击败本层全部怪物", gameInstanceSceneData = { succeedConditionData = "monster_2000=15&monster_2001=4&monster_2006=1",
			 consumptionItems = { item = { itemCount = 37, itemRefId = "item_zhenmoling_1", }, }, 
			 conditionField = { "quest_27", "quest_28", "quest_29", }, }, 	},
					["S213"] = { refId = "S213", property = { sceneRefId = "S213", succeedType = 1,},  mapId = 213, description = "击败本层全部怪物", gameInstanceSceneData = { succeedConditionData = "monster_2000=10&monster_2001=10&monster_2002=5",
			 consumptionItems = { item = { itemCount = 40, itemRefId = "item_zhenmoling_1", }, }, 
			 conditionField = { "quest_30", "quest_31", "quest_32", }, }, 	},
					["S214"] = { refId = "S214", property = { sceneRefId = "S214", succeedType = 1,},  mapId = 214, description = "击败本层全部怪物", gameInstanceSceneData = { succeedConditionData = "monster_2000=10&monster_2001=5&monster_2002=10",
			 consumptionItems = { item = { itemCount = 50, itemRefId = "item_zhenmoling_1", }, }, 
			 conditionField = { "quest_33", "quest_34", "quest_35", }, }, 	},
					["S215"] = { refId = "S215", property = { sceneRefId = "S215", succeedType = 1,},  mapId = 215, description = "击败本层全部怪物", gameInstanceSceneData = { succeedConditionData = "monster_2000=15&monster_2001=8&monster_2007=1",
			 consumptionItems = "", 
			 conditionField = { "quest_36", "quest_37", "quest_38", }, }, 	},
			}	},
			}}
}
