-- NAME: Ins_3
-- TIME: 2014.6.16-19:1:31
-- Generated by editor

GameData = GameData or {}
GameData.Ins_3= {
	["Ins_3"] = { refId = "Ins_3", instanceType = 1, name = "净化虫巢", introduce = "55级副本，摧毁虫穴，奖励丰厚更有聚宝盆碎片", suggestlevel = 55,
			configData = {
					["game_instance"] = { refId = "game_instance", name = "Ins_3 任务总表",
			configData = {
					["Ins_3"] = { refId = "Ins_3", gameInstanceData = { openDetailsData = "00:00:00|86400",
			 structureDetails = { "I103", }, },  property = { questRefId = "", timesADay = 2, timesAWeek = 0, level = 40, isTeam = 0, name = "地底虫巢",},  name = "地底虫巢", description = "击败全部怪物可完成副本，点击挂机按钮事半功倍，点击出口按钮即可离开副本。",	},
			}	},
					["game_instance_quest"] = { refId = "game_instance_quest", name = "副本任务表",
			configData = {
					["quest_1"] = { refId = "quest_1", name = "消除虫祸", description = "击败10个{mouster_8035}。", property = { questType = 1, rewardImmediately = 0,},  questData = {
			 orderField = { { killCount = 10, monsterRefId = "monster_8035", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 75000, }, }, }, 	},
					["quest_2"] = { refId = "quest_2", name = "深入清洁", description = "击败{monster_8039}。", property = { questType = 1, rewardImmediately = 0,},  questData = {
			 orderField = { { killCount = 11, monsterRefId = "monster_8039", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 75000, }, }, }, 	},
					["quest_3"] = { refId = "quest_3", name = "虫王之死", description = "击败{monster_8041}。", property = { questType = 1, rewardImmediately = 0,},  questData = {
			 orderField = { { killCount = 1, monsterRefId = "monster_8041", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 450000, }, }, }, 	},
			}	},
					["game_instance_scene"] = { refId = "game_instance_scene", name = "副本层总表",
			configData = {
					["I103"] = { refId = "I103", property = { sceneRefId = "S103", succeedType = 1,},  mapId = 103, description = "本层无通关条件，随便打，打得越多，经验越多", gameInstanceSceneData = { succeedConditionData = "monster_8041=1&monster_8035=10&monster_8039=11",
			 consumptionItems = "", 
			 conditionField = { "quest_1", "quest_2", "quest_3", }, }, 	},
			}	},
			}}
}
