-- NAME: Ins_4
-- TIME: 2014.6.16-19:1:31
-- Generated by editor

GameData = GameData or {}
GameData.Ins_4= {
	["Ins_4"] = { refId = "Ins_4", instanceType = 1, name = "王座之战", introduce = "60级副本，击退骷髅，奖励丰厚更有定身戒指碎片", suggestlevel = 60,
			configData = {
					["game_instance"] = { refId = "game_instance", name = "Ins_4 任务总表",
			configData = {
					["Ins_4"] = { refId = "Ins_4", gameInstanceData = { openDetailsData = "00:00:00|86400",
			 structureDetails = { "I104", }, },  property = { questRefId = "", timesADay = 2, timesAWeek = 0, level = 40, isTeam = 0, name = "骷髅精灵",},  name = "骷髅精灵", description = "击败全部怪物可完成副本，点击挂机按钮事半功倍，点击出口按钮即可离开副本。",	},
			}	},
					["game_instance_quest"] = { refId = "game_instance_quest", name = "副本任务表",
			configData = {
					["quest_1"] = { refId = "quest_1", name = "击败掷斧骷髅", description = "击败10个{mouster_8018}。", property = { questType = 1, rewardImmediately = 0,},  questData = {
			 orderField = { { killCount = 10, monsterRefId = "monster_8018", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 100000, }, }, }, 	},
					["quest_2"] = { refId = "quest_2", name = "击败骷髅战将", description = "击败{monster_8019}。", property = { questType = 1, rewardImmediately = 0,},  questData = {
			 orderField = { { killCount = 10, monsterRefId = "monster_8019", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 50000, }, }, }, 	},
					["quest_3"] = { refId = "quest_3", name = "骷髅精灵之死", description = "击败{monster_8020}。", property = { questType = 1, rewardImmediately = 0,},  questData = {
			 orderField = { { killCount = 1, monsterRefId = "monster_8020", orderType = 1, },}, 
			 rewardField = { propertyReward = { exp = 750000, }, }, }, 	},
			}	},
					["game_instance_scene"] = { refId = "game_instance_scene", name = "副本层总表",
			configData = {
					["I104"] = { refId = "I104", property = { sceneRefId = "S104", succeedType = 1,},  mapId = 104, description = "击败全部怪物", gameInstanceSceneData = { succeedConditionData = "monster_8018=10&monster_8019=10&monster_8020=1",
			 consumptionItems = "", 
			 conditionField = { "quest_1", "quest_2", "quest_3", }, }, 	},
			}	},
			}}
}
